Repository nginx/agent, pull requests merged in 2022-12, with the labels that each got.

#127 fixed metrics
  Makefile
  README.md
  examples/grafana-metrics/Makefile
  nginx-agent.conf
  scripts/tls/gen_cert.sh
  scripts/tls/gen_cnf.sh
  sdk/config_helpers_test.go
  src/plugins/agent_api.go
  test/performance/user_workflow_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
Labels: bug, documentation, dependencies

#131 Block config apply
  sdk/proto/dp_software_details.pb.go
  sdk/proto/dp_software_details.proto
  src/core/config/defaults.go
  src/extensions/advanced-metrics/pkg/publisher/publisher_test.go
  src/extensions/nginx-app-protect/nap/const.go
  src/extensions/nginx-app-protect/nap/types.go
  src/plugins/agent_api.go
  src/plugins/commander_test.go
  src/plugins/dataplane_status.go
  src/plugins/events.go
  src/plugins/events_test.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/user_workflow_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/dp_software_details.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/dp_software_details.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/const.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/proto/dp_software_details.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/dp_software_details.proto
Labels: dependencies

#126 README updates
  README.md
  docs/agent-flow.png
Labels: documentation

#136 Fix docs url to link to GitHub
  .github/workflows/release-branch.yml
  scripts/packages/nginx-agent.service
Labels: bug

#138 Fix arch of apk packages
  Makefile.packaging
Labels: bug

#144 fix: check if app_protect_metadata's nap version is empty first.
  src/plugins/nginx.go
Labels: bug

#130 Add config apply rest endpoint
  .github/workflows/ci.yml
  main.go
  sdk/proto/command.pb.go
  sdk/proto/command.proto
  src/core/config/types.go
  src/core/nginx.go
  src/core/topics.go
  src/plugins/agent_api.go
  src/plugins/agent_api_test.go
  src/plugins/dataplane_status.go
  src/plugins/dataplane_status_test.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/command.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/command.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/nginx.go
  test/utils/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/proto/command.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/command.proto
Labels: enhancement, dependencies

#145 fix: detect nginx upgrade
  src/core/nginx.go
  src/core/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: bug, documentation, dependencies

#150 Fix packaging config for 2.20
  .nfpm.yaml
  scripts/.local-nfpm.yaml
  scripts/packages/postinstall.sh
Labels: bug, documentation, dependencies

#152 rhel packages not to be replaced
  .nfpm.yaml
  scripts/.local-nfpm.yaml
  scripts/packages/preinstall.sh
Labels: bug

#153 fix: reorder Makefile targets to made help the default
  Makefile
Labels: good first issue, chore

#149 WIP: Remove the default gRPC configuration for the nginx-agent
  README.md
  docs/content/getting-started.md
  nginx-agent.conf
Labels: documentation
