Repository nginx/agent, pull requests merged in 2023-10, with the labels that each got.

#476 Update CLI flags documentation
  hugo/content/configuration-overview.md
Labels: documentation

#485 deprecate system.mem.used.all metric
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/mem.go
  src/core/metrics/sources/mem_test.go
  test/integration/api/api_test.go
  test/integration/grpc/grpc_config_apply_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/mem.go
Labels: bug, dependencies, chore

#489 Update NGINX plugin to read NGINX config on startup
  README.md
  examples/grafana-metrics/nginx-agent.conf
  hugo/content/getting-started.md
  main.go
  src/core/pipe.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/api/api_test.go
  test/integration/api/nginx-agent.conf
  test/integration/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: documentation, dependencies, chore

#493 profile.cgo
  profile.cgo
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: dependencies, chore

#494 fix: Tolerate additional fields in App Protect yaml files
  src/extensions/nginx-app-protect/nap/attack_signatures.go
  src/extensions/nginx-app-protect/nap/attack_signatures_test.go
  src/extensions/nginx-app-protect/nap/threat_campaigns.go
  src/extensions/nginx-app-protect/nap/threat_campaigns_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/attack_signatures.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/threat_campaigns.go
Labels: bug, dependencies, chore

#492 Add link in docs on how to configure logrotation
  hugo/content/getting-started.md
Labels: documentation

#497 Add queue size configuration parameter
  hugo/content/configuration-overview.md
  main.go
  sdk/agent/config/config_helpers.go
  src/core/config/config.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/core/pipe.go
  src/core/pipe_test.go
  src/plugins/agent_api_test.go
  src/plugins/common.go
  src/plugins/extensions.go
  src/plugins/features.go
  src/plugins/process_watcher.go
  src/plugins/process_watcher_test.go
  test/component/nginx-app-protect/monitoring/monitoring_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/metrics_test.go
  test/performance/plugins_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/common.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/extensions.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/process_watcher.go
  vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
Labels: chore

#499 fix worker metrics
  README.md
  src/core/metrics/sources/nginx_plus.go
  src/core/metrics/sources/nginx_plus_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
Labels: bug, documentation, dependencies, chore

#490 Add CLI arg to set dynamic config path
  hugo/content/configuration-overview.md
  hugo/content/getting-started.md
  main.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/plugins/events.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
Labels: documentation, dependencies, chore
