Repository nginx/agent, pull requests merged in 2023-06, with the labels that each got.

#327 fixed bullseye docker image
  .gitignore
  Makefile
  scripts/docker/nginx-plus/debian/Dockerfile
Labels: bug

#300 Enable disable features
  Makefile
  main.go
  sdk/agent/config/config_helpers.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/metrics/collectors/nginx.go
  src/core/metrics/collectors/nginx_test.go
  src/core/mock_pipe.go
  src/core/pipe.go
  src/core/topics.go
  src/plugins/agent_api.go
  src/plugins/agent_api_test.go
  src/plugins/commander.go
  src/plugins/commander_test.go
  src/plugins/config_reader.go
  src/plugins/dataplane_status.go
  src/plugins/events.go
  src/plugins/extensions.go
  src/plugins/features.go
  src/plugins/features_test.go
  src/plugins/file_watcher.go
  src/plugins/file_watcher_throttling.go
  src/plugins/metrics.go
  src/plugins/metrics_test.go
  src/plugins/metrics_throlling.go
  src/plugins/metrics_throlling_test.go
  src/plugins/nginx.go
  src/plugins/nginx_counter.go
  src/plugins/nginx_test.go
  src/plugins/process_watcher.go
  src/plugins/process_watcher_test.go
  src/plugins/registration.go
  src/plugins/registration_test.go
  test/component/agent_api_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/performance/metrics_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/mock_pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/extensions.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/file_watcher.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/file_watcher_throttling.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_throlling.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx_counter.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/process_watcher.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/registration.go
  vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
Labels: documentation, enhancement, dependencies, chore

#325 doc: add comments for each field in the SecurityViolationEvent proto definition
  docs/proto/events.md
  sdk/proto/events/event.pb.go
  sdk/proto/events/event.proto
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Labels: documentation, dependencies, chore

#332 chore: update deprecated API calls
  sdk/grpc/grpc.go
  src/core/config/commands.go
  src/core/environment_test.go
  src/core/network/network.go
  src/extensions/nginx-app-protect/nap/attack_signatures.go
  src/extensions/nginx-app-protect/nap/nap_metadata_test.go
  src/extensions/nginx-app-protect/nap/threat_campaigns.go
  src/plugins/agent_api_test.go
  src/plugins/file_watcher_test.go
  test/integration/reader_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/commands.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/network/network.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/attack_signatures.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/threat_campaigns.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/symbols.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/tls.go
  test/utils/symbols.go
  test/utils/tls.go
  vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
Labels: dependencies, chore

#329 Output mount point in error message
  src/core/metrics/sources/disk.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/disk.go
Labels: dependencies, chore

#335 fix: fixes segfault when process is TERMed
  main.go
Labels: bug, chore

#331 fix: fix Linux default network interface parsing
  src/core/network/network.go
  src/core/network/network_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/network/network.go
Labels: bug, dependencies, chore

#326 Update Go version
  README.md
  hugo/content/getting-started.md
Labels: documentation

#320 Close controller before exiting
  main.go
  sdk/proto/events/event.proto
  src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Labels: documentation, dependencies, chore

#345 Fix warnings when purging agent
  scripts/packages/postremove.sh
Labels: bug, dependencies, chore

#341 Fix Packaging
  .github/workflows/ci.yml
  .github/workflows/release-branch.yml
  Makefile.packaging
  scripts/packages/packager/signed-entrypoint.sh
Labels: bug

#338 Fix segmentation fault during agent registration
  src/plugins/commander.go
  src/plugins/commander_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
Labels: bug

#344 Update selinux policy
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
Labels: bug

#330 Skip warnings on non-file log destinations
  src/core/nginx.go
  src/core/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Labels: dependencies, chore

#348 added fix for listen directives in stub status and plus API configs
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug, dependencies, chore

#349 Fix: specified predefined access log format (#340)
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug, dependencies, chore

#323 Add NGINX Agent Uninstall Doc
  hugo/content/uninstall.md
Labels: documentation

#356 fix: bump hugo theme to 0.33.0
  hugo/go.mod
Labels: bug, dependencies

#351 Monitor NGINX logs for alert messages after NGINX reload
  src/core/nginx.go
  src/core/nginx_test.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#346 Fix access log parsing for custom log format
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_access_log_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
Labels: bug

#343 Ignore directives feature
  sdk/config_apply.go
  sdk/config_apply_test.go
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  src/core/config/config.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/core/environment_test.go
  src/core/nginx.go
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  src/extensions/nginx-app-protect/nap/nap_metadata_test.go
  src/plugins/agent_api.go
  src/plugins/metrics.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_apply.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_apply.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/config_apply.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: enhancement

#359 fixed tooling to pull from vendor and go.mod
  Makefile
  go.mod
  go.sum
  scripts/tools.go
  sdk/client/client.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/client.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/client.go
  vendor/github.com/alvaroloes/enumer/.gitignore
  vendor/github.com/alvaroloes/enumer/LICENSE
  vendor/github.com/alvaroloes/enumer/README.md
  vendor/github.com/alvaroloes/enumer/enumer.go
  vendor/github.com/alvaroloes/enumer/sql.go
  vendor/github.com/alvaroloes/enumer/stringer.go
  vendor/github.com/nginx/agent/sdk/v2/client/client.go
  vendor/github.com/pascaldekloe/name/.travis.yml
  vendor/github.com/pascaldekloe/name/LICENSE
  vendor/github.com/pascaldekloe/name/README.md
  vendor/github.com/pascaldekloe/name/case.go
  vendor/modules.txt
Labels: bug, documentation, dependencies, chore

#360 Add timeout to integration tests setup
  test/integration/utils/test_container_utils.go
Labels: chore
