Repository nginx/agent, pull requests merged in 2023-05, with the labels that each got.

#288 add coverage to XML parsing in NAP Monitoring
  src/extensions/nginx-app-protect/monitoring/processor/nap.go
  src/extensions/nginx-app-protect/monitoring/processor/processor_test.go
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_cookie_length.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_header_length.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_header_text.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_parameter_data.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_url_header_data.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_violation_cookie_data.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/xml_violation_url_data.log.txt
  test/component/nginx-app-protect/monitoring/monitoring_test.go
  test/component/nginx-app-protect/monitoring/testData/events-out/xml_parameter_data.json
  test/component/nginx-app-protect/monitoring/testData/events-out/xml_violation_cookie_data.json
  test/component/nginx-app-protect/monitoring/testData/events-out/xml_violation_header_data.json
  test/component/nginx-app-protect/monitoring/testData/events-out/xml_violation_url_data.json
  test/component/nginx-app-protect/monitoring/testData/logs-in/xml_parameter_data.xml
  test/component/nginx-app-protect/monitoring/testData/logs-in/xml_violation_cookie_data.xml
  test/component/nginx-app-protect/monitoring/testData/logs-in/xml_violation_header_data.xml
  test/component/nginx-app-protect/monitoring/testData/logs-in/xml_violation_url_data.xml
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/monitoring/processor/nap.go
Labels: dependencies, chore

#301 Support GetNetOverflow in linux
  src/core/network/network.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/network/network.go
Labels: dependencies, chore

#270 Fix empty access item when log format is changed
  src/core/metrics/collectors/nginx.go
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_error_log.go
  src/plugins/metrics.go
  src/plugins/metrics_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_error_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
Labels: bug, documentation, dependencies, chore

#278 Fix handing of setting access_log off;
  sdk/backoff_test.go
  sdk/certificates.go
  sdk/config_apply.go
  sdk/config_apply_test.go
  src/core/nginx.go
  src/core/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/certificates.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_apply.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/certificates.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_apply.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/certificates.go
  vendor/github.com/nginx/agent/sdk/v2/config_apply.go
Labels: bug, dependencies, chore

#316 Packages scripts refactor
  nginx-agent.conf
  scripts/packages/manifest
  scripts/packages/postinstall.sh
  scripts/packages/preinstall.sh
  scripts/selinux/README.md
Labels: documentation

#296 Update OS Support Docs
  hugo/content/technical-specifications.md
Labels: documentation

#314 Fix processing error for pause message on agent config topic
  go.work.sum
  src/plugins/commander.go
  src/plugins/commander_test.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
Labels: bug, documentation, dependencies, chore

#309 Add docs for installing nginx-agent from repository
  README.md
  hugo/content/changelog.md
  hugo/content/community.md
  hugo/content/dev-environment-setup.md
  hugo/content/getting-started.md
  hugo/content/installation-github.md
  hugo/content/installation-oss.md
  hugo/content/installation-plus.md
  hugo/content/technical-specifications.md
  hugo/content/upgrading.md
Labels: documentation

#305 Fix packager script post deinstall.
  scripts/packages/packager/local-entrypoint.sh
  scripts/packages/packager/signed-entrypoint.sh
Labels: bug
