Repository nginx/agent, pull requests merged in 2023-09, with the labels that each got.

#449 Update selinux readme
  scripts/selinux/README.md
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: documentation, dependencies

#465 Only create metrics sender if a metric reporter is already created
  main.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: dependencies, chore

#467 Fix SELinux Policy & Fix SELinux README
  scripts/selinux/README.md
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
Labels: bug, documentation

#464 Add support for file actions during a config apply
  src/core/environment.go
  src/core/environment_test.go
  src/core/fake_environment_test.go
  src/core/nginx.go
  src/core/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/test/utils/environment.go
  test/performance/environment_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/environment.go
  test/utils/environment.go
Labels: dependencies, chore

#471 fix: ensure fullpath
  src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Labels: bug, dependencies, chore

#461 Add worker conn metrics
  go.mod
  go.sum
  src/core/config/defaults.go
  src/core/metrics/collectors/nginx_test.go
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/nginx_plus.go
  src/core/metrics/sources/nginx_plus_test.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
  test/performance/vendor/github.com/nginxinc/nginx-plus-go-client/client/nginx.go
  test/performance/vendor/modules.txt
  vendor/github.com/nginxinc/nginx-plus-go-client/client/nginx.go
  vendor/modules.txt
Labels: dependencies, chore

#468 Fix version for forked repo
  Makefile
Labels: bug

#466 Update file watcher to ignore .swx files
  src/plugins/file_watcher.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/file_watcher.go
Labels: dependencies, chore

#474 Check Simplemetrics is not empty
  src/core/metrics/aggregate.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/aggregate.go
Labels: dependencies, chore

#480 Fix config apply
  main.go
  src/plugins/common.go
  src/plugins/common_test.go
  src/plugins/events.go
  src/plugins/events_test.go
  src/plugins/features.go
  src/plugins/features_test.go
  test/performance/plugins_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/common.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
Labels: bug

#477 Add error log if duplicate NGINX IDs are found
  src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Labels: dependencies, chore

#469 Add tests for additional SSL directives and key algorithms. #276
  scripts/tls/gen_cert.sh
  sdk/config_helpers_test.go
Labels: dependencies, chore

#479 call underlying os.Hostname instead of the entire hostInfo gopsutil call
  src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: dependencies, chore

#481 Use singleflight for caching environment.go calls
  sdk/config_helpers_test.go
  src/core/environment.go
  src/core/fake_environment_test.go
  src/core/metrics/collectors/system.go
  src/core/metrics/sources/disk.go
  src/core/metrics/sources/disk_test.go
  src/core/nginx.go
  src/plugins/dataplane_status.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/test/utils/environment.go
  test/integration/vendor/golang.org/x/sync/singleflight/singleflight.go
  test/integration/vendor/modules.txt
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/system.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/disk.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/environment.go
  test/performance/vendor/golang.org/x/sync/singleflight/singleflight.go
  test/performance/vendor/modules.txt
  test/utils/environment.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: dependencies, chore
