Repository nginx/agent, pull requests merged in 2023-03, with the labels that each got.

#210 Print NginxConfig in JSON format for debug and trace levels
  src/core/nginx.go
  src/plugins/nginx.go
Labels: chore

#214 Add plus upstream metrics
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_oss.go
  src/core/metrics/sources/nginx_oss_test.go
  src/core/metrics/sources/nginx_plus.go
  src/core/metrics/sources/nginx_plus_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_oss.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
Labels: dependencies, chore

#212 Add almalinux support
  .github/workflows/ci.yml
  Makefile
  Makefile.containers
  Makefile.packaging
  examples/grafana-metrics/docker-compose.yml
  scripts/docker/agentless-entrypoint.sh
  scripts/docker/entrypoint.sh
  scripts/docker/nginx-oss/agentless-entrypoint.sh
  scripts/docker/nginx-oss/deb/Dockerfile
  scripts/docker/nginx-oss/rpm/Dockerfile
  scripts/docker/nginx-plus/alpine/Dockerfile
  scripts/docker/nginx-plus/amazonlinux/Dockerfile
  scripts/docker/nginx-plus/centos/Dockerfile
  scripts/docker/nginx-plus/debian/Dockerfile
  scripts/docker/nginx-plus/oraclelinux/Dockerfile
  scripts/docker/nginx-plus/redhatenterprise/Dockerfile
  scripts/docker/nginx-plus/suse/Dockerfile
  scripts/docker/nginx-plus/ubuntu/Dockerfile
  src/core/metrics/sources/nginx_plus.go
  src/core/metrics/sources/nginx_plus_test.go
  test/integration/api/docker-compose-deb.yml
  test/integration/api/docker-compose-rpm.yml
  test/integration/install/docker-compose-deb.yml
  test/integration/install/docker-compose-rpm.yml
Labels: chore

#222 fix: uri and request parsing;
  src/extensions/nginx-app-protect/monitoring/collector/nap.go
  src/extensions/nginx-app-protect/monitoring/collector/nap_test.go
  src/extensions/nginx-app-protect/monitoring/processor/nap.go
  src/extensions/nginx-app-protect/monitoring/processor/nap_test.go
  src/extensions/nginx-app-protect/monitoring/processor/testdata/expanded_nap_waf.log.txt
  src/extensions/nginx-app-protect/monitoring/processor/testdata/uri_request_contain_escaped_comma.log.txt
  src/plugins/nap_monitoring.go
  test/component/nginx-app-protect/monitoring/monitoring_test.go
  test/component/nginx-app-protect/monitoring/testData/events-out/expanded_nap_waf.log.txt.out
  test/component/nginx-app-protect/monitoring/testData/logs-in/expanded_nap_waf.log.txt
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/monitoring/collector/nap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/monitoring/processor/nap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nap_monitoring.go
Labels: bug, dependencies, chore

#244 Send agent version in grpc metadata
  main.go
Labels: chore

#251 remove fields from trace logging
  src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Labels: dependencies, chore

#241 deprecate-nginx-id-from-violation
  docs/proto/events.md
  sdk/proto/events/event.pb.go
  sdk/proto/events/event.proto
  src/extensions/nginx-app-protect/monitoring/processor/processor.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/monitoring/processor/processor.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Labels: documentation, dependencies, chore

#234 Add lineCount support to dirmap files
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  sdk/files/file_helpers.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/files/file_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/files/file_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/files/file_helpers.go
Labels: dependencies, chore

#256 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#238 Fix cache level size info for systems data
  src/core/environment.go
  src/core/environment_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: bug, dependencies, chore

#239 Fix architecture and uname
  docs/proto/proto.md
  sdk/proto/host.pb.go
  sdk/proto/host.proto
  src/core/environment.go
  src/core/environment_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/host.pb.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/host.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/host.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/host.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  vendor/github.com/nginx/agent/sdk/v2/proto/host.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/host.proto
Labels: bug, documentation, dependencies, chore

#237 Fix OS release information in system details
  go.mod
  go.sum
  sdk/proto/events/event.proto
  src/core/environment.go
  src/core/environment_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  vendor/github.com/evilmartians/lefthook/CHANGELOG.md
  vendor/github.com/evilmartians/lefthook/internal/config/command.go
  vendor/github.com/evilmartians/lefthook/internal/config/load.go
  vendor/github.com/evilmartians/lefthook/internal/config/script.go
  vendor/github.com/evilmartians/lefthook/internal/git/repository.go
  vendor/github.com/evilmartians/lefthook/internal/lefthook/runner/executor.go
  vendor/github.com/evilmartians/lefthook/internal/lefthook/runner/prepare_command.go
  vendor/github.com/evilmartians/lefthook/internal/lefthook/runner/runner.go
  vendor/github.com/evilmartians/lefthook/internal/version/version.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  vendor/modules.txt
Labels: bug

#247 fix: made build target to work predictably
  Makefile
Labels: bug

#258 Pid drain check
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#260 Fix flaky install/uninstall test
  test/integration/install/install_uninstall_test.go
Labels: bug, chore

#261 Add wrapper to execute shell commands
  go.mod
  go.sum
  go.work.sum
  sdk/proto/events/event.proto
  src/core/environment.go
  src/core/environment_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  vendor/github.com/evilmartians/lefthook/CHANGELOG.md
  vendor/github.com/evilmartians/lefthook/internal/templates/hook.tmpl
  vendor/github.com/evilmartians/lefthook/internal/version/version.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  vendor/modules.txt
Labels: documentation, dependencies, chore

#271 added waitgroup done in tests
  sdk/client/commander_test.go
Labels: chore
