Repository nginx/agent, pull requests merged in 2023-01, with the labels that each got.

#159 Updated GetStatusApiInfo function to combine nginx configs before transversing them
  sdk/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug

#157 feat: directory map actions
  sdk/Makefile
  sdk/proto/common.pb.go
  sdk/proto/common.proto
  src/core/nginx.go
  src/core/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/Makefile
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/common.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/common.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/Makefile
  vendor/github.com/nginx/agent/sdk/v2/proto/common.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/common.proto
Labels: enhancement, dependencies

#166 fix: skip delete if file doesn't exists
  src/core/nginx.go
  src/core/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
Labels: bug, dependencies

#167 Add Support for NAP Precompiled Publication
  go.mod
  src/core/config/config.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/extensions/nginx-app-protect/nap/attack_signatures.go
  src/extensions/nginx-app-protect/nap/attack_signatures_test.go
  src/extensions/nginx-app-protect/nap/nap.go
  src/extensions/nginx-app-protect/nap/nap_content.go
  src/extensions/nginx-app-protect/nap/nap_content_test.go
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  src/extensions/nginx-app-protect/nap/threat_campaigns.go
  src/extensions/nginx-app-protect/nap/threat_campaigns_test.go
  src/extensions/nginx-app-protect/nap/types.go
  src/plugins/nginx.go
  src/plugins/nginx_app_protect.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/attack_signatures.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_content.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/threat_campaigns.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx_app_protect.go
Labels: chore

#170 Move nap_content.go logic into the agent sdk
  go.mod
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  src/extensions/nginx-app-protect/nap/nap_content.go
  src/extensions/nginx-app-protect/nap/nap_content_test.go
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_content.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: dependencies

#146 Add Swagger API Docs
  Makefile
  README.md
  docs/swagger.json
  go.mod
  go.sum
  go.work.sum
  sdk/proto/nginx.pb.go
  sdk/proto/nginx.proto
  src/plugins/agent_api.go
  src/plugins/agent_api_test.go
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/nginx.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/nginx.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/rs/cors/LICENSE
  test/performance/vendor/github.com/rs/cors/README.md
  test/performance/vendor/github.com/rs/cors/cors.go
  test/performance/vendor/github.com/rs/cors/utils.go
  test/performance/vendor/modules.txt
  vendor/github.com/nginx/agent/sdk/v2/proto/nginx.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/nginx.proto
  vendor/github.com/rs/cors/LICENSE
  vendor/github.com/rs/cors/README.md
  vendor/github.com/rs/cors/cors.go
  vendor/github.com/rs/cors/utils.go
  vendor/modules.txt
Labels: documentation, dependencies

#168 GitHub release workflow improvements
  .chglog.yml
  .github/workflows/ci.yml
  .github/workflows/release-branch.yml
  README.md
  docs/CHANGELOG.md
  hugo/content/changelog.md
  scripts/changelog.yml
Labels: documentation, chore

#174 Fix freebsd package path in release branch workflow
  .github/workflows/release-branch.yml
Labels: bug

#177 Update release workflow package upload
  .github/workflows/release-branch.yml
  Makefile.packaging
  scripts/packages/packager/signed-entrypoint.sh
Labels: bug

#176 fix: Handle case when NAP metadata doesn't exist
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  src/extensions/nginx-app-protect/nap/nap_metadata_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
Labels: bug

#179 fix: Handle case when NAP metadata directory doesn't exist
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  src/extensions/nginx-app-protect/nap/nap_metadata_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
Labels: bug, dependencies, chore

#180 Add upstream connection time and header time metrics
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/cpu.go
  src/core/metrics/sources/cpu_test.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_access_log_test.go
  src/core/metrics/sources/nginx_error_log.go
  src/core/metrics/sources/nginx_error_log_test.go
  src/core/metrics/sources/nginx_oss.go
  src/core/metrics/sources/nginx_oss_test.go
  src/core/metrics/sources/tailer/tailer.go
  src/core/metrics/sources/tailer/tailer_test.go
  test/integration/go.mod
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/cpu.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_error_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_oss.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/tailer/tailer.go
Labels: dependencies, chore

#158 feat: podman support
  Makefile
  Makefile.containers
  Makefile.packaging
  scripts/docker/nginx-oss/ubuntu/Dockerfile
  scripts/docker/nginx-plus/alpine/Dockerfile
  scripts/docker/nginx-plus/amazonlinux/Dockerfile
  scripts/docker/nginx-plus/centos/Dockerfile
  scripts/docker/nginx-plus/debian/Dockerfile
  scripts/docker/nginx-plus/oraclelinux/Dockerfile
  scripts/docker/nginx-plus/redhatenterprise/Dockerfile
  scripts/docker/nginx-plus/suse/Dockerfile
  scripts/docker/nginx-plus/ubuntu/Dockerfile
  scripts/packages/packager/Dockerfile
  test/integration/api/api_test.go
  test/integration/api/docker-compose.yml
Labels: enhancement, chore
