Repository nginx/agent, pull requests merged in 2023-07, with the labels that each got.

#362 Average memory metrics instead of summing
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/nginx_worker.go
  src/core/metrics/sources/nginx_worker_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_worker.go
Labels: dependencies, chore

#364 Fix integer overflow
  src/core/metrics/sources/nginx_worker.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_worker.go
Labels: bug

#372 Auto dependency checks
  .github/dependabot.yml
  go.work.sum
  src/core/metrics/sources/nginx_worker.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_worker.go
Labels: dependencies, chore

#365 Add capture integration test docker logs
  .github/workflows/ci.yml
  test/integration/utils/test_container_utils.go
Labels: chore

#361 Remove duplicate code from enable/disable features & add tests
  .github/workflows/ci.yml
  Makefile
  sdk/client/commander_test.go
  sdk/config_helpers.go
  src/core/mock_pipe.go
  src/core/pipe.go
  src/core/pipe_test.go
  src/extensions/nginx_app_protect.go
  src/plugins/commander.go
  src/plugins/commander_test.go
  src/plugins/config_reader.go
  src/plugins/config_reader_test.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  test/integration/features/docker-compose-apk.yml
  test/integration/features/docker-compose-deb.yml
  test/integration/features/docker-compose-rpm.yml
  test/integration/features/features_test.go
  test/integration/features/nginx.conf
  test/integration/features/test_configs/nginx-agent-config.conf
  test/integration/features/test_configs/nginx-agent-counting.conf
  test/integration/features/test_configs/nginx-agent-metrics.conf
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/mock_pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx_app_protect.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: enhancement, dependencies, chore

#384 Use ParseInt instead of Atoi when converting process id string to an int
  src/core/metrics/sources/nginx_worker.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_worker.go
Labels: dependencies, chore

#363 Support ltsv
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/tailer/tailer.go
  src/core/tailer/tailer_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/tailer/tailer.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: dependencies, chore

#381 Populate loopback interface metrics to a metric report
  src/core/metrics/sources/net_io.go
  src/core/metrics/sources/net_io_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/net_io.go
Labels: dependencies, chore

#387 Bump runc
  go.mod
  go.sum
  go.work.sum
  sdk/go.mod
  sdk/go.sum
  sdk/vendor/github.com/sirupsen/logrus/README.md
  sdk/vendor/github.com/sirupsen/logrus/writer.go
  sdk/vendor/modules.txt
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/github.com/docker/distribution/.dockerignore
  test/integration/vendor/github.com/docker/distribution/.golangci.yml
  test/integration/vendor/github.com/docker/distribution/.mailmap
  test/integration/vendor/github.com/docker/distribution/Dockerfile
  test/integration/vendor/github.com/docker/distribution/Makefile
  test/integration/vendor/github.com/docker/distribution/docker-bake.hcl
  test/integration/vendor/github.com/docker/distribution/reference/reference.go
  test/integration/vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
  test/integration/vendor/github.com/docker/distribution/registry/api/v2/errors.go
  test/integration/vendor/github.com/docker/distribution/registry/client/repository.go
  test/integration/vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  test/integration/vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  test/integration/vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  test/integration/vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  test/integration/vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  test/integration/vendor/github.com/opencontainers/image-spec/specs-go/version.go
  test/integration/vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  test/integration/vendor/github.com/sirupsen/logrus/README.md
  test/integration/vendor/github.com/sirupsen/logrus/writer.go
  test/integration/vendor/modules.txt
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/sirupsen/logrus/README.md
  test/performance/vendor/github.com/sirupsen/logrus/writer.go
  test/performance/vendor/modules.txt
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: documentation, dependencies, chore

#353 Add Dockerfiles & docker-compose files for official OSS & Plus images
  Makefile
  hugo/content/installation-oss.md
  hugo/content/installation-plus.md
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/Dockerfile.mainline
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/docker-compose.yml
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/entrypoint.sh
  scripts/docker/official/nginx-plus-with-nginx-agent/alpine/Dockerfile
  scripts/docker/official/nginx-plus-with-nginx-agent/alpine/docker-compose.yml
  scripts/docker/official/nginx-plus-with-nginx-agent/alpine/entrypoint.sh
Labels: documentation, enhancement

#393 Improve enable/disable features
  sdk/agent/config/config_helpers.go
  src/core/pipe.go
  src/plugins/commander.go
  src/plugins/commander_test.go
  src/plugins/config_reader.go
  src/plugins/config_reader_test.go
  src/plugins/extensions.go
  src/plugins/extensions_test.go
  src/plugins/features.go
  src/plugins/features_test.go
  src/plugins/metrics_sender.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/extensions.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
Labels: enhancement, dependencies, chore

#399 fix amazon packaging
  Makefile.packaging
Labels: bug

#398 Fix docker issues
  Makefile
  scripts/docker/nginx-plus/ubuntu/Dockerfile
Labels: bug, documentation, dependencies, chore

#382 Fix backoff settings
  main.go
  sdk/client/client.go
  sdk/client/commander.go
  src/core/config/config.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/plugins/commander.go
  src/plugins/config_reader.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/client.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/client.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  vendor/github.com/nginx/agent/sdk/v2/client/client.go
  vendor/github.com/nginx/agent/sdk/v2/client/commander.go
Labels: bug

#385 Monitor NGINX logs for critical & error messages after NGINX reload
  src/core/nginx.go
  src/core/nginx_test.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#409 Fix selinux policy on RHEL 8
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
Labels: bug

#411 fix pipeline
  .github/workflows/ci.yml
Labels: bug

#396 fix integration test failures
  .github/workflows/ci.yml
  scripts/docker/agentless-entrypoint.sh
  scripts/docker/entrypoint.sh
  test/integration/utils/test_container_utils.go
Labels: chore

#413 Fix selinux policy on RHEL 8
  .github/workflows/ci.yml
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
Labels: bug

#401 Fix grpc reconnect logic
  go.work.sum
  sdk/client/commander.go
  sdk/client/commander_test.go
  sdk/client/metric_reporter.go
  sdk/client/metric_reporter_test.go
  src/core/nginx.go
  src/core/nginx_test.go
  src/plugins/commander.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Labels: bug

#412 Unit test failures
  sdk/client/commander.go
  sdk/client/commander_test.go
  sdk/client/controller_test.go
  sdk/client/errors.go
  sdk/client/metric_reporter.go
  sdk/client/metric_reporter_test.go
  sdk/go.mod
  sdk/go.sum
  sdk/vendor/github.com/google/uuid/.travis.yml
  sdk/vendor/github.com/google/uuid/CONTRIBUTING.md
  sdk/vendor/github.com/google/uuid/CONTRIBUTORS
  sdk/vendor/github.com/google/uuid/LICENSE
  sdk/vendor/github.com/google/uuid/README.md
  sdk/vendor/github.com/google/uuid/dce.go
  sdk/vendor/github.com/google/uuid/doc.go
  sdk/vendor/github.com/google/uuid/hash.go
  sdk/vendor/github.com/google/uuid/marshal.go
  sdk/vendor/github.com/google/uuid/node.go
  sdk/vendor/github.com/google/uuid/node_js.go
  sdk/vendor/github.com/google/uuid/node_net.go
  sdk/vendor/github.com/google/uuid/null.go
  sdk/vendor/github.com/google/uuid/sql.go
  sdk/vendor/github.com/google/uuid/time.go
  sdk/vendor/github.com/google/uuid/util.go
  sdk/vendor/github.com/google/uuid/uuid.go
  sdk/vendor/github.com/google/uuid/version1.go
  sdk/vendor/github.com/google/uuid/version4.go
  sdk/vendor/modules.txt
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/errors.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/errors.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  vendor/github.com/nginx/agent/sdk/v2/client/errors.go
  vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Labels: documentation, dependencies, chore

#420 Upgrade nginx-hugo-theme to support newer versions of Hugo
  hugo/.gitignore
  hugo/README.md
  hugo/config/development/config.toml
  hugo/config/production/config.toml
  hugo/config/staging/config.toml
  hugo/go.mod
  hugo/go.sum
  hugo/go.work.sum
  hugo/makefile
  hugo/netlify.toml
Labels: documentation, dependencies

#350 fix: use host architecture to determine FreeBSD ABI
  scripts/packages/packager/local-entrypoint.sh
  scripts/packages/packager/signed-entrypoint.sh
Labels: bug
