Repository nginx/agent, pull requests merged in 2023-12, with the labels that each got.

#516 Restrict NAP file/dir permissions
  src/extensions/nginx-app-protect/nap/nap.go
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  src/extensions/nginx-app-protect/nap/nap_metadata_test.go
  src/extensions/nginx-app-protect/nap/nap_test.go
  src/extensions/php_fpm_metrics.go
  src/extensions/php_fpm_metrics_test.go
  src/extensions/prometheus-metrics/prometheus_exporter.go
  src/extensions/prometheus-metrics/prometheus_exporter_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/php_fpm_metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/prometheus-metrics/prometheus_exporter.go
Labels: dependencies, chore

#526 Update upgrade documentation
  hugo/content/upgrading.md
Labels: documentation

#527 chore: rename hugo folder to site, fix product naming
  site/.gitignore
  site/README.md
  site/config/_default/config.toml
  site/config/development/config.toml
  site/config/production/config.toml
  site/config/staging/config.toml
  site/content/_index.md
  site/content/changelog.md
  site/content/community.md
  site/content/configuration-overview.md
  site/content/dev-environment-setup.md
  site/content/docker-images.md
  site/content/getting-started.md
  site/content/installation-github.md
  site/content/installation-oss.md
  site/content/installation-plus.md
  site/content/overview.md
  site/content/technical-specifications.md
  site/content/uninstall.md
  site/content/upgrading.md
  site/data/.gitkeep
  site/data/layouts/.gitkeep
  site/go.mod
  site/go.sum
  site/go.work
  site/go.work.sum
  site/makefile
  site/md-linkcheck-config.json
  site/mdlint.json
  site/netlify.toml
  site/static/.gitkeep
  site/static/agent-flow.png
  site/static/grafana-dashboard-example.png
Labels: bug, documentation, dependencies
