Repository nginx/agent, pull requests merged in 2023-11, with the labels that each got.

#510 Bump integration and performance test dependency versions
  go.mod
  go.sum
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/github.com/docker/docker/api/types/versions/compare.go
  test/integration/vendor/github.com/klauspost/compress/zstd/enc_best.go
  test/integration/vendor/modules.txt
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/client.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/const.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/consumer.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/events.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/filestore.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/jetstream.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/jetstream_api.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/jetstream_cluster.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/jetstream_events.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/memstore.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/monitor.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/mqtt.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/opts.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/raft.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/reload.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/route.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/server.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/signal_windows.go
  test/performance/vendor/github.com/nats-io/nats-server/v2/server/stream.go
  test/performance/vendor/github.com/nats-io/nkeys/nkeys.go
  test/performance/vendor/github.com/nats-io/nkeys/xkeys.go
  test/performance/vendor/modules.txt
  vendor/github.com/docker/docker/api/types/versions/compare.go
  vendor/github.com/klauspost/compress/zstd/enc_best.go
  vendor/modules.txt
Labels: dependencies

#502 Add commander retry lock
  sdk/client/commander.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  vendor/github.com/nginx/agent/sdk/v2/client/commander.go
Labels: dependencies, chore

#498 Fix user agent request header to have the correct agent version
  src/core/grpc.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/grpc.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/grpc.go
Labels: bug

#511 Fix alpine plus dockerfile on alpine>=3.17
  scripts/docker/nginx-plus/alpine/Dockerfile
Labels: bug

#352 fix: avoid stopping nginx-agent service on package upgrade
  README.md
  scripts/.local-nfpm.yaml
  scripts/packages/nginx-agent.openrc
  scripts/packages/postinstall.sh
  scripts/packages/postremove.sh
  scripts/packages/postupgrade.sh
  scripts/packages/preinstall.sh
  scripts/packages/preremove.sh
Labels: bug, documentation

#520 Fix SELinux Policy
  scripts/selinux/nginx_agent.fc
  scripts/selinux/nginx_agent.if
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
Labels: bug

#524 Replace mockgen
  COPYRIGHT
  Makefile
  go.mod
  go.sum
  scripts/tools.go
  src/extensions/advanced-metrics/aggregator/aggregator.go
  src/extensions/advanced-metrics/aggregator/aggregator_test.go
  src/extensions/advanced-metrics/aggregator/mocks/aggregator_mock.go
  src/extensions/advanced-metrics/ingester/ingester.go
  src/extensions/advanced-metrics/ingester/ingester_test.go
  src/extensions/advanced-metrics/ingester/mocks/ingester_mock.go
  src/extensions/advanced-metrics/reader/mocks/net_mocks.go
  src/extensions/advanced-metrics/reader/mocks/reader_mock.go
  src/extensions/advanced-metrics/reader/reader.go
  src/extensions/advanced-metrics/reader/reader_test.go
  src/extensions/advanced-metrics/reader/worker_test.go
  src/extensions/advanced-metrics/tables/mocks/staging_table_mocks.go
  src/extensions/advanced-metrics/tables/staging_table.go
  src/extensions/advanced-metrics/tables/staging_table_test.go
  test/integration/go.sum
  test/integration/vendor/github.com/nginx/agent/v2/COPYRIGHT
  test/integration/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/aggregator/aggregator.go
  test/integration/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/ingester/ingester.go
  test/integration/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/reader/reader.go
  test/integration/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/tables/staging_table.go
  test/performance/go.sum
  test/performance/vendor/github.com/nginx/agent/v2/COPYRIGHT
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/aggregator/aggregator.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/ingester/ingester.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/reader/reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced-metrics/tables/staging_table.go
  vendor/github.com/golang/mock/mockgen/version.1.11.go
  vendor/go.uber.org/mock/AUTHORS
  vendor/go.uber.org/mock/CONTRIBUTORS
  vendor/go.uber.org/mock/LICENSE
  vendor/go.uber.org/mock/gomock/call.go
  vendor/go.uber.org/mock/gomock/callset.go
  vendor/go.uber.org/mock/gomock/controller.go
  vendor/go.uber.org/mock/gomock/doc.go
  vendor/go.uber.org/mock/gomock/matchers.go
  vendor/go.uber.org/mock/mockgen/generic_go118.go
  vendor/go.uber.org/mock/mockgen/generic_notgo118.go
  vendor/go.uber.org/mock/mockgen/mockgen.go
  vendor/go.uber.org/mock/mockgen/model/model.go
  vendor/go.uber.org/mock/mockgen/parse.go
  vendor/go.uber.org/mock/mockgen/reflect.go
  vendor/go.uber.org/mock/mockgen/version.go
  vendor/modules.txt
Labels: dependencies, chore

#519 Restrict config apply directory permissions
  src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: dependencies, chore

#517 Fix permissions for log file and dynamic config directory
  src/core/config/config.go
  src/core/logger/log.go
  src/core/os.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/os.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/logger/log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/os.go
Labels: bug, dependencies, chore

#518 Fix server example in sdk to have timeout
  sdk/examples/server.go
Labels: bug, chore
