Repository nginx/agent, pull requests merged in 2023-02, with the labels that each got.

#194 Fix error parsing access log request
  sdk/proto/events/event.pb.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_access_log_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.pb.go
Labels: bug

#200 more checks around ppid
  src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: dependencies, chore

#211 fix: move go installation step
  hugo/content/getting-started.md
  hugo/content/installation.md
Labels: documentation

#195 Update developer environment section in README
  README.md
  hugo/content/dev-environment-setup.md
Labels: documentation

#196 Add rockylinux support
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  scripts/docker/nginx-oss/rockylinux/Dockerfile
  test/integration/api/api_test.go
  test/integration/api/docker-compose-deb.yml
  test/integration/api/docker-compose-rpm.yml
  test/integration/install/docker-compose-deb.yml
  test/integration/install/docker-compose-rpm.yml
  test/integration/install/install_uninstall_test.go
Labels: chore

#216 Fix error reading exe process information
  src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: bug

#219 Fix docs to reference packages in current release
  README.md
  hugo/content/installation.md
Labels: documentation

#220 Add assertion for no error level logs in tests
  Makefile
  test/integration/api/api_test.go
  test/integration/install/install_uninstall_test.go
  test/integration/utils/test_container_utils.go
Labels: chore

#203 add upstream status metrics
  src/core/metrics/metrics_util.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_access_log_test.go
  src/core/metrics/sources/tailer/tailer.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/tailer/tailer.go
Labels: dependencies, chore
