Repository nginx/agent, pull requests merged in 2023-04, with the labels that each got.

#269 Add Supported distributions
  hugo/content/technical-specifications.md
Labels: documentation

#275 Reduce logging verbosity
  sdk/proto/events/event.proto
  src/core/environment.go
  src/core/metrics/sources/cgroup/cgroup_swap.go
  src/core/nginx.go
  src/core/nginx_test.go
  src/extensions/advanced_metrics.go
  src/extensions/advanced_metrics_test.go
  src/extensions/nap_monitoring.go
  src/extensions/nap_monitoring_test.go
  src/extensions/nginx_app_protect.go
  src/extensions/nginx_app_protect_test.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/cgroup/cgroup_swap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced_metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nap_monitoring.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx_app_protect.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Labels: dependencies, chore

#279 Fix potential race
  sdk/proto/events/event.proto
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Labels: bug, dependencies, chore

#280 fix: Pass correct variable for lscpu command to work
  src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: bug

#273 Add alpine 3.17 support
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  scripts/docker/agentless-entrypoint.sh
  scripts/docker/entrypoint.sh
  scripts/docker/nginx-oss/apk/Dockerfile
  scripts/docker/nginx-oss/deb/Dockerfile
  scripts/docker/nginx-oss/rpm/Dockerfile
  sdk/proto/events/event.proto
  test/integration/api/api_test.go
  test/integration/api/docker-compose-apk.yml
  test/integration/api/nginx.conf
  test/integration/install/docker-compose-apk.yml
  test/integration/install/install_uninstall_test.go
  test/integration/install/nginx.conf
  test/integration/utils/test_container_utils.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
  vendor/github.com/nginx/agent/sdk/v2/proto/events/event.proto
Labels: dependencies, chore

#282 Update NGINX monitor function to handle monitoring multiple NGINX error logs
  src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#289 Fix replace usage of flaky epel repo
  scripts/docker/nginx-oss/rpm/Dockerfile
Labels: bug

#292 remove pids draining
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#298 Fix Vendoring
  test/integration/go.sum
  test/integration/vendor/github.com/go-logr/logr/.golangci.yaml
  test/integration/vendor/github.com/go-logr/logr/discard.go
  test/integration/vendor/github.com/go-logr/logr/funcr/funcr.go
  test/integration/vendor/github.com/go-logr/logr/logr.go
  test/integration/vendor/github.com/imdario/mergo/map.go
  test/integration/vendor/github.com/imdario/mergo/merge.go
  test/integration/vendor/github.com/imdario/mergo/mergo.go
  test/integration/vendor/github.com/spf13/cobra/.golangci.yml
  test/integration/vendor/github.com/spf13/cobra/Makefile
  test/integration/vendor/github.com/spf13/cobra/README.md
  test/integration/vendor/github.com/spf13/cobra/active_help.go
  test/integration/vendor/github.com/spf13/cobra/args.go
  test/integration/vendor/github.com/spf13/cobra/bash_completions.go
  test/integration/vendor/github.com/spf13/cobra/bash_completionsV2.go
  test/integration/vendor/github.com/spf13/cobra/cobra.go
  test/integration/vendor/github.com/spf13/cobra/command.go
  test/integration/vendor/github.com/spf13/cobra/command_notwin.go
  test/integration/vendor/github.com/spf13/cobra/command_win.go
  test/integration/vendor/github.com/spf13/cobra/completions.go
  test/integration/vendor/github.com/spf13/cobra/fish_completions.go
  test/integration/vendor/github.com/spf13/cobra/flag_groups.go
  test/integration/vendor/github.com/spf13/cobra/powershell_completions.go
  test/integration/vendor/github.com/spf13/cobra/projects_using_cobra.md
  test/integration/vendor/github.com/spf13/cobra/shell_completions.go
  test/integration/vendor/github.com/spf13/cobra/shell_completions.md
  test/integration/vendor/github.com/spf13/cobra/user_guide.md
  test/integration/vendor/github.com/spf13/cobra/zsh_completions.go
  test/integration/vendor/modules.txt
Labels: bug, documentation, dependencies, chore

#268 move agent-dynamic.conf to /var/lib/nginx-agent
  README.md
  examples/grafana-metrics/nginx-agent.conf
  hugo/content/getting-started.md
  main.go
  nginx-agent.conf
  scripts/packages/postinstall.sh
  scripts/packages/postremove.sh
  scripts/packages/preinstall.sh
  sdk/client/commander_test.go
  src/core/config/config.go
  src/core/config/defaults.go
  test/integration/api/nginx-agent.conf
  test/integration/install/install_uninstall_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
Labels: documentation, dependencies, chore
