Repository nginx/agent, pull requests merged in 2023-08, with the labels that each got.

#419 Reload NGINX after rolling back NGINX configuration changes
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: bug

#414 enable log rotation
  .nfpm.yaml
  README.md
  hugo/content/configuration-overview.md
  nginx-agent.conf
  scripts/.local-nfpm.yaml
  scripts/nginx-agent.logrotate
Labels: documentation, chore

#418 Add documentation for docker images
  README.md
  hugo/content/changelog.md
  hugo/content/community.md
  hugo/content/configuration-overview.md
  hugo/content/dev-environment-setup.md
  hugo/content/docker-images.md
  hugo/content/getting-started.md
  hugo/content/installation-github.md
  hugo/content/installation-oss.md
  hugo/content/installation-plus.md
  hugo/content/technical-specifications.md
  hugo/content/uninstall.md
Labels: documentation

#423 Update how the SDK parses NGINX API server directive
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug

#424 Update nginx access & error log metric sources to only report metrics that are available
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_access_log_test.go
  src/core/metrics/sources/nginx_error_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_error_log.go
Labels: bug

#427 blank log path should not log to file
  src/core/config/config_test.go
  src/core/config/defaults.go
  src/core/logger/log.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/logger/log.go
Labels: dependencies, chore

#432 More tidying of code and memory leaks
  main.go
  src/core/environment.go
  src/plugins/dataplane_status.go
  src/plugins/metrics.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/advanced-metrics/metric_gen/generator.go
  test/performance/environment_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
Labels: dependencies, chore

#429 Improve error logging for gRPC EOF errors
  sdk/client/commander.go
  sdk/client/metric_reporter.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Labels: dependencies, chore

#436 fix: bump hugo theme to 0.35.0
  hugo/config/_default/config.toml
  hugo/go.mod
  hugo/go.sum
Labels: bug, dependencies

#430 chore: cert directives for ssl_client_certificate and ssl_trusted_certificate
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: chore

#435 feat: Add ADM resource name dimensions
  src/extensions/advanced_metrics.go
  test/performance/advanced-metrics/fake_agent/agent.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced_metrics.go
Labels: chore

#433 Fix how status API URL is determined when both stub status and NGINX Plus APIs are configured
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug

#426 Send error to UI when config async is disabled
  src/plugins/config_reader.go
  src/plugins/events.go
  src/plugins/features.go
  src/plugins/features_test.go
  src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#431 Fix intermittent issue where the reloadNginx function never finishes
  src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: bug

#440 make deps and remove duplicate if statement
  .github/workflows/release-branch.yml
  scripts/packages/packager/Dockerfile
  src/plugins/nginx.go
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/.golangci.yml
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/analyze.go
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/analyze_map.go
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/build.go
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/errors.go
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/lex.go
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/parse.go
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/util.go
  test/integration/vendor/modules.txt
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/.golangci.yml
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/analyze.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/analyze_map.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/build.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/errors.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/lex.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/parse.go
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/util.go
  test/performance/vendor/modules.txt
Labels: dependencies, chore

#437 Race condition reloading
  src/core/nginx.go
  src/core/nginx_test.go
  src/core/topics.go
  src/plugins/dataplane_status.go
  src/plugins/metrics.go
  src/plugins/metrics_test.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#445 fix: fix logic for parsing absolute path to nginx config file
  sdk/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug

#450 fix for dash during upgrade
  src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: bug, dependencies, chore

#447 Improve status API detection and validation
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug, dependencies, chore

#448 Rebuild selinux policy on RHEL 8
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
Labels: bug

#453 Add metric sender feature
  main.go
  sdk/agent/config/config_helpers.go
  sdk/config_helpers.go
  src/core/metrics/collectors/nginx.go
  src/core/topics.go
  src/plugins/features.go
  src/plugins/features_test.go
  src/plugins/metrics.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  src/plugins/metrics_test.go
  src/plugins/metrics_throlling.go
  src/plugins/metrics_throlling_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/metrics_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_throlling.go
  vendor/github.com/nginx/agent/sdk/v2/agent/config/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: enhancement, dependencies, chore

#457 Revert "Merge release-2.28.1 back into main (#455)"
  scripts/selinux/nginx_agent.pp
  scripts/selinux/nginx_agent.te
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: dependencies, chore

#444 Remove Ubuntu 18.04, Alpine 3.13 and Alpine 3.14 OS support
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  hugo/content/technical-specifications.md
Labels: documentation, chore

#443 Add Alpine 3.18 support
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  hugo/content/technical-specifications.md
Labels: documentation, chore
