Repository nginx/agent, pull requests merged in 2024-01, with the labels that each got.

#538 feat: added the new OS support for NGINX R31
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  site/content/technical-specifications.md
Labels: documentation, enhancement

#537 New project structure
  .github/workflows/ci.yml
  .github/workflows/label-pr.yml
  Makefile
  Makefile.tools
  api/grpc/instances/instances.pb.go
  api/grpc/instances/instances.proto
  api/http/common/common.gen.go
  api/http/common/common.yaml
  api/http/dataplane/client.gen.go
  api/http/dataplane/dataplane-api.yaml
  api/http/dataplane/dataplane.gen.go
  cmd/agent/main.go
  go.mod
  go.sum
  internal/app.go
  internal/app_test.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/bus/topics.go
  internal/datasource/nginx/nginx.go
  internal/datasource/nginx/nginx_test.go
  internal/datasource/nginx/process/process.go
  internal/datasource/nginx/process/process_test.go
  internal/datasource/os/exec/exec.go
  internal/datasource/os/exec/mock_exec.go
  internal/datasource/os/process.go
  internal/model/os/os.go
  internal/plugin/dataplane_server.go
  internal/plugin/dataplane_server_test.go
  internal/plugin/process_monitor.go
  internal/plugin/process_monitor_test.go
  internal/service/instance.go
  internal/service/instance_test.go
  internal/service/mock_instance.go
  internal/uuid/uuid.go
  internal/uuid/uuid_test.go
  lefthook.yml
  v3/cmd/agent/main.go
  v3/internal/models/nginx.go
Labels: dependencies, chore

#539 Add agent configuration functionality
  Makefile
  cmd/agent/main.go
  go.mod
  go.sum
  internal/app.go
  internal/app_test.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/config/command.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/logger/logger.go
  internal/logger/logger_test.go
  internal/plugin/dataplane_server.go
  internal/plugin/dataplane_server_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/plugin/process_monitor.go
  nginx-agent.conf
Labels: dependencies, chore

#540 Config Download
  api/grpc/instances/file.pb.go
  api/grpc/instances/file.proto
  api/grpc/instances/instances.pb.go
  internal/client/http_config_client.go
  internal/client/http_config_client_test.go
  internal/client/mock_http_config_client.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/datasource/config_writer.go
  internal/datasource/config_writer_test.go
  internal/datasource/os/files.go
  internal/datasource/os/files_test.go
  nginx-agent.conf
Labels: chore

#542 Add update instance config endpoint
  Makefile
  api/http/common/common.gen.go
  api/http/common/common.yaml
  api/http/common/error.go
  api/http/common/error_test.go
  api/http/dataplane/client.gen.go
  api/http/dataplane/dataplane-api.yaml
  api/http/dataplane/dataplane.gen.go
  internal/bus/topics.go
  internal/datasource/datasource.go
  internal/datasource/mock_datasource.go
  internal/plugin/dataplane_server.go
  internal/plugin/dataplane_server_test.go
  internal/plugin/instance_monitor.go
  internal/plugin/instance_monitor_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/service/instance.go
  internal/service/instance_test.go
  internal/service/mock_instance.go
Labels: chore

#547 Add config plugin for parsing dataplane configuration.
  Makefile
  api/grpc/instances/file.pb.go
  api/grpc/instances/instances.pb.go
  api/grpc/instances/instances.proto
  api/http/common/common.gen.go
  api/http/common/common.yaml
  go.mod
  go.sum
  internal/bus/fake_message_pipe.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/bus/topics.go
  internal/client/clientfakes/fake_http_config_client_interface.go
  internal/client/http_config_client.go
  internal/datasource/config_writer_test.go
  internal/datasource/datasource.go
  internal/datasource/nginx/nginx.go
  internal/datasource/nginx/nginx_test.go
  internal/datasource/nginx/process.go
  internal/datasource/nginx/process/process.go
  internal/datasource/nginx/process_test.go
  internal/datasource/os/exec/exec.go
  internal/datasource/os/exec/execfakes/fake_exec_interface.go
  internal/datasource/os/files.go
  internal/datasource/os/files_test.go
  internal/datasource/os/process.go
  internal/model/config.go
  internal/model/instance.go
  internal/model/os.go
  internal/plugin/config.go
  internal/plugin/config_test.go
  internal/plugin/dataplane_server.go
  internal/plugin/dataplane_server_test.go
  internal/plugin/instance.go
  internal/plugin/instance_monitor.go
  internal/plugin/instance_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/plugin/process_monitor.go
  internal/plugin/process_monitor_test.go
  internal/service/config.go
  internal/service/config/config.go
  internal/service/config/config_test.go
  internal/service/config/configfakes/fake_dataplane_config.go
  internal/service/config/nginx.go
  internal/service/config/nginx_gateway_fabric.go
  internal/service/config/nginx_test.go
  internal/service/config_test.go
  internal/service/instance.go
  internal/service/instance/instance.go
  internal/service/instance/instancefakes/fake_dataplane_instance_service.go
  internal/service/instance/nginx.go
  internal/service/instance/nginx_gateway_fabric.go
  internal/service/instance/nginx_test.go
  internal/service/instance_test.go
  internal/service/mock_instance.go
  internal/service/servicefakes/fake_config_service_interface.go
  internal/service/servicefakes/fake_instance_service_interface.go
Labels: dependencies, chore

#548 feat: Agent Docs IA refactor
  site/content/configuration/_index.md
  site/content/configuration/configuration-overview.md
  site/content/configuration/encrypt-communication.md
  site/content/contribute/_index.md
  site/content/contribute/community.md
  site/content/contribute/dev-environment-setup.md
  site/content/installation-upgrade/_index.md
  site/content/installation-upgrade/container-environments/_index.md
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/installation-upgrade/container-environments/docker-support.md
  site/content/installation-upgrade/getting-started.md
  site/content/installation-upgrade/installation-github.md
  site/content/installation-upgrade/installation-oss.md
  site/content/installation-upgrade/installation-plus.md
  site/content/installation-upgrade/uninstall.md
  site/content/installation-upgrade/upgrade.md
  site/content/overview.md
  site/content/technical-specifications.md
Labels: documentation, enhancement

#551 validate config & reload nginx
  api/grpc/instances/file.pb.go
  api/grpc/instances/instances.pb.go
  api/grpc/instances/instances.proto
  api/http/common/common.gen.go
  api/http/common/common.yaml
  internal/client/clientfakes/fake_http_config_client_interface.go
  internal/client/http_config_client.go
  internal/client/http_config_client_test.go
  internal/config/config.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/datasource/config_writer.go
  internal/datasource/config_writer_test.go
  internal/datasource/nginx/process.go
  internal/datasource/os/file_helpers.go
  internal/datasource/os/file_helpers_test.go
  internal/datasource/os/files.go
  internal/datasource/os/files_test.go
  internal/service/config/config.go
  internal/service/config/configfakes/fake_dataplane_config.go
  internal/service/config/nginx.go
  internal/service/config/nginx_gateway_fabric.go
  internal/service/config/nginx_test.go
  internal/service/instance/nginx.go
  internal/service/instance/nginx_test.go
  internal/service/instance_test.go
Labels: chore
