Repository nginx/agent, pull requests merged in 2024-03, with the labels that each got.

#584 Restore agent container information from nms docs
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/technical-specifications.md
Labels: documentation

#575 Update instance configuration integration test
  Makefile
  internal/client/http_config_client.go
  internal/client/http_config_client_test.go
  test/config/nginx/nginx-with-test-location.conf
  test/config/nginx_config.go
  test/helpers.go
  test/integration/data_plane_api_test.go
  test/mock/Dockerfile
  test/mock/cmd/main.go
  test/test_containers_utils.go
Labels: chore

#582 Add rollback & change configuration status
  .testcoverage.yaml
  api/grpc/instances/configurations.pb.go
  api/grpc/instances/configurations.proto
  api/grpc/instances/file.pb.go
  api/grpc/instances/instances.pb.go
  api/http/dataplane/client.gen.go
  api/http/dataplane/data-plane-api.yaml
  internal/bus/topics.go
  internal/datasource/config/cache.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/datasource/config/configfakes/fake_file_cache_interface.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/config/data_plane_config_service.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_gateway_fabric_config_service.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/servicefakes/fake_config_service_interface.go
  test/integration/data_plane_api_test.go
Labels: chore

#587 feat: improve docker docs
  site/content/installation-upgrade/container-environments/docker-images.md
Labels: documentation, enhancement

#588 Imporve unit test coverage
  .testcoverage.yaml
  internal/bus/topics.go
  internal/model/metrics.go
  internal/model/modelfakes/fake_exporter.go
  internal/model/modelfakes/fake_metrics_producer.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/metrics_plugin_test.go
  internal/plugin/plugin_manager_test.go
  internal/service/config/nginx_gateway_fabric_config_service_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/instance/instancefakes/fake_data_plane_instance_service.go
  test/helpers.go
Labels: chore

#589 Fixes to Rollback
  internal/datasource/config/config_writer.go
  internal/service/config_service.go
  internal/service/config_service_test.go
Labels: bug, chore

#590 Added proto gRPC connection logic for a Management Plane Server. Also added skeleton proto definitions for the Management Plane Interface
  Makefile
  Makefile.tools
  api/grpc/buf.yaml
  api/grpc/instances/configurations.pb.go
  api/grpc/instances/file.pb.go
  api/grpc/instances/instances.pb.go
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.proto
  api/grpc/mpi/v1/command_grpc.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/common.proto
  api/http/dataplane/client.gen.go
  docs/proto/protos.md
  go.mod
  go.sum
  internal/app.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/datasource/config/config_writer_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/plugin/process_monitor_plugin_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service_test.go
  test/config/agent/nginx-agent-with-data-plane-api.conf
  test/config/agent/nginx-config-with-grpc-client.conf
  test/config/nginx_config.go
  test/integration/data_plane_api_test.go
  test/integration/grpc_connection_test.go
  test/mock/Dockerfile
  test/mock/grpc/Dockerfile
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_plane_grpc_server.go
  test/mock/http/Dockerfile
  test/mock/http/cmd/main.go
  test/mock/http/mock-management-plane-api.yaml
  test/mock/http/mock_management_plane.gen.go
  test/mock/http/mock_management_plane_server.go
  test/test_containers_utils.go
Labels: documentation, dependencies, chore

#593 Centralize proto data for testing purposes
  internal/client/http_config_client_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/datasource/config/cache_test.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/host/file_helpers_test.go
  internal/datasource/nginx/log_tailer_test.go
  internal/logger/logger_test.go
  internal/metrics/export/otel.go
  internal/metrics/export/otel_test.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/process_monitor_plugin_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service_test.go
  test/data.go
  test/helpers/id_generator_utils.go
  test/helpers/os_utils.go
  test/helpers/test_containers_utils.go
  test/integration/data_plane_api_test.go
  test/integration/grpc_connection_test.go
  test/protos/common.go
  test/protos/instances.go
  test/types/config.go
Labels: chore

#591 Add performance benchmark tests
  .github/workflows/ci.yml
  Makefile
  Makefile.tools
  internal/plugin/config_plugin_test.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_config_service_benchmark_test.go
  internal/service/instance/nginx_instance_service_benchmark_test.go
  test/config/nginx/mime.types
Labels: chore

#594 fixed the graceful shutdown of the app and the DataPlane API server
  internal/app.go
  internal/config/defaults.go
  internal/metrics/export/otel.go
  internal/metrics/export/otel_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/metrics_plugin_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/process_monitor_plugin.go
Labels: bug, chore

#592 fix: add additional container checks during instance registration
  src/core/environment.go
Labels: documentation, chore

#595 Config Apply Delete File
  .golangci.yml
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
Labels: chore

#601 chore: Add the 2.32.2 Changelog to the docs website
  site/content/changelog.md
Labels: documentation

#603 Update unit test names
  internal/client/http_config_client_test.go
  internal/datasource/config/cache_test.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/nginx/nginx_process_test.go
  internal/logger/logger_test.go
  internal/metrics/export/otel_test.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/metrics_plugin_test.go
  internal/plugin/plugin_manager_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service_test.go
  internal/service/instance/nginx_instance_service_test.go
Labels: chore

#596 replace duplicate isContainer call
  src/core/environment.go
  src/core/environment_test.go
  src/core/fake_environment_test.go
  src/extensions/advanced-metrics/aggregator/mocks/aggregator_mock.go
  src/extensions/advanced-metrics/ingester/mocks/ingester_mock.go
  src/extensions/advanced-metrics/reader/mocks/net_mocks.go
  src/extensions/advanced-metrics/reader/mocks/reader_mock.go
  src/extensions/advanced-metrics/tables/mocks/staging_table_mocks.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/test/utils/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/environment.go
  test/utils/environment.go
Labels: dependencies, chore

#600 Add mock management plane file service
  Makefile
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.proto
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
  api/grpc/mpi/v1/files_grpc.pb.go
  docs/proto/protos.md
  test/mock/grpc/Dockerfile
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_plane_grpc_file_server.go
Labels: documentation, chore

#607 fix unit test
  src/core/environment.go
  src/core/environment_test.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: bug, dependencies, chore

#608 Refactor how context is used
  cmd/agent/main.go
  internal/app.go
  internal/bus/fake_message_pipe.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/client/http_config_client_test.go
  internal/config/config.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/host/process.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/instance_plugin.go
  internal/plugin/instance_plugin_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/metrics_plugin_test.go
  internal/plugin/process_monitor_plugin.go
  internal/plugin/process_monitor_plugin_test.go
  internal/service/config/nginx_config_service.go
  internal/service/config_service_test.go
  test/integration/data_plane_api_test.go
  test/integration/grpc_connection_test.go
Labels: chore

#605 Add logging to NGINX API http requests
  sdk/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: dependencies, chore

#612 Fix user workflow performance tests
  test/performance/user_workflow_test.go
Labels: bug, chore

#613 Add more configs for ParseConfig performance test
  internal/service/config/nginx_config_service_benchmark_test.go
  test/config/nginx/nginx-with-10k-lines.conf
  test/config/nginx/nginx-with-1k-lines.conf
  test/config/nginx/nginx-with-2k-lines.conf
  test/config/nginx/nginx-with-3k-lines.conf
Labels: chore

#614 Add default temp config directory for mock management plane grpc file server
  Makefile
  internal/logger/logger.go
  internal/logger/logger_test.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_plane_grpc_file_server.go
Labels: chore

#604 feat: Add Support for NAP 5
  docs/proto/proto.md
  sdk/proto/nap.pb.go
  sdk/proto/nap.proto
  src/extensions/nginx-app-protect/nap/const.go
  src/extensions/nginx-app-protect/nap/nap.go
  src/extensions/nginx-app-protect/nap/nap_metadata.go
  src/extensions/nginx-app-protect/nap/nap_metadata_test.go
  src/extensions/nginx-app-protect/nap/nap_release.go
  src/extensions/nginx-app-protect/nap/nap_release_test.go
  src/extensions/nginx-app-protect/nap/nap_test.go
  src/extensions/nginx-app-protect/nap/releases.go
  src/extensions/nginx-app-protect/nap/types.go
  src/extensions/nginx_app_protect.go
  src/extensions/nginx_app_protect_test.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/nap.pb.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/nap.proto
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/nap.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/nap.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/const.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_metadata.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap_release.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/releases.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx_app_protect.go
  vendor/github.com/nginx/agent/sdk/v2/proto/nap.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/nap.proto
Labels: documentation, enhancement, dependencies, chore

#598 fix Advanced Metrics
  src/core/os.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/os.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/os.go
Labels: bug, dependencies, chore

#616 Add subscribe RPC support in mock management plane
  api/grpc/instances/configurations.pb.go
  api/grpc/instances/file.pb.go
  api/grpc/instances/instances.pb.go
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command_grpc.pb.go
  api/grpc/mpi/v1/common.pb.go
  test/mock/grpc/mock_management_plane_grpc_server.go
Labels: chore

#615 Add data plane status rpc to mock management plane
  test/mock/grpc/mock_management_plane_grpc_server.go
Labels: chore

#619 Replace instances.Instance proto with v1.Instance proto
  api/grpc/instances/instances.pb.go
  api/grpc/instances/instances.proto
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/model/instance.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/instance_plugin_test.go
  internal/service/config/data_plane_config_service_test.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_config_service_benchmark_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/instance/data_plane_instance_service.go
  internal/service/instance/instancefakes/fake_data_plane_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service.go
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_test.go
  internal/service/instance_service.go
  internal/service/instance_service_test.go
  internal/service/servicefakes/fake_instance_service_interface.go
Labels: documentation, chore

#617 Keep looking for master process
  scripts/docker/nginx-oss/deb/Dockerfile
  src/plugins/registration.go
  src/plugins/registration_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/registration.go
Labels: dependencies, chore

#622 chore: add 2.33.0 changelog
  site/content/changelog.md
Labels: documentation

#620 Build packages for integration test
  .github/workflows/ci.yml
  Makefile
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files_grpc.pb.go
Labels: documentation, chore

#621 Leak detection
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files_grpc.pb.go
  cmd/agent/package_test.go
  go.mod
  go.sum
Labels: dependencies, chore
