Repository nginx/agent, pull requests merged in 2024-09, with the labels that each got.

#816 Stop official image tests running on forks
  .github/workflows/ci.yml
Labels: v3.x

#813 Bump documentation theme version
  site/go.mod
  site/go.sum
Labels: dependencies

#812 Fix make image targets
  Makefile
  scripts/docker/nginx-oss/apk/Dockerfile
  scripts/docker/nginx-oss/deb/Dockerfile
  scripts/docker/nginx-oss/rpm/Dockerfile
  scripts/docker/nginx-plus/almalinux/Dockerfile
  scripts/docker/nginx-plus/alpine/Dockerfile
  scripts/docker/nginx-plus/amazonlinux/Dockerfile
  scripts/docker/nginx-plus/centos/Dockerfile
  scripts/docker/nginx-plus/debian/Dockerfile
  scripts/docker/nginx-plus/oraclelinux/Dockerfile
  scripts/docker/nginx-plus/redhatenterprise/Dockerfile
  scripts/docker/nginx-plus/rockylinux/Dockerfile
  scripts/docker/nginx-plus/suse/Dockerfile
  scripts/docker/nginx-plus/ubuntu/Dockerfile
  scripts/packages/postinstall.sh
Labels: bug, v2.x

#818 Increase integration test retries
  internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
  test/integration/grpc_management_plane_api_test.go
Labels: chore, v3.x

#819 Fix debian oss image
  scripts/docker/nginx-oss/deb/Dockerfile
Labels: bug, v2.x

#826 Set log level to debug for inetegration tests
  test/integration/api/nginx-agent.conf
  test/integration/features/test_configs/nginx-agent-config.conf
  test/integration/features/test_configs/nginx-agent-counting.conf
  test/integration/features/test_configs/nginx-agent-metrics.conf
  test/integration/grpc/grpc_config_apply_test.go
Labels: chore

#825 Fix install-tools make target
  Makefile.tools
  README.md
  go.mod
  go.sum
  internal/collector/factories.go
  internal/collector/factories_test.go
  internal/collector/settings.go
  internal/collector/settings_test.go
  internal/datasource/host/exec/exec.go
  internal/watcher/health/nginx_health_watcher_operator.go
  internal/watcher/process/process_operator.go
  test/integration/grpc_management_plane_api_test.go
Labels: bug, documentation, dependencies, chore, v3.x

#784 Add automatic changelog generation in release workflow
  .github/workflows/release-branch.yml
Labels: documentation, v2.x

#806 Add OTel collector log file
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  scripts/testing/load/Dockerfile
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/types/config.go
Labels: chore, v3.x

#830 Updated NGINX Plus receiver logging to use OTel collector logger
  internal/collector/nginxplusreceiver/factory.go
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/otel_collector_plugin.go
Labels: chore

#832 Change process parser log level
  internal/watcher/instance/nginx_process_parser.go
Labels: chore, v3.x

#810 Race conditions fixes
  .github/workflows/ci.yml
  nginx-agent.conf
  sdk/client/metric_reporter.go
  sdk/config_helpers.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/environment.go
  src/core/metrics/sources/disk.go
  src/core/metrics/sources/net_io.go
  src/core/metrics/sources/nginx_access_log.go
  src/core/metrics/sources/nginx_error_log.go
  src/core/nginx.go
  src/core/pipe.go
  src/plugins/commander.go
  src/plugins/config_reader.go
  src/plugins/dataplane_status.go
  src/plugins/metrics.go
  src/plugins/metrics_throlling.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/integration/vendor/github.com/nginx/agent/v2/test/utils/nginx.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/disk.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/net_io.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_access_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_error_log.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_throlling.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/nginx.go
  test/utils/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug, dependencies, chore, v2.x

#828 Add CLA bot workflow
  .github/workflows/f5-cla.yml
  CONTRIBUTING.md
Labels: documentation, chore

#837 Check error in file watcher
  internal/collector/nginxossreceiver/internal/metadata/generated_status.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
  internal/watcher/file/file_watcher_service.go
  internal/watcher/file/file_watcher_service_test.go
Labels: chore, v3.x

#841 Refactor docker images
  scripts/docker/nginx-plus/debian/Dockerfile
  site/content/installation-upgrade/container-environments/docker-images.md
Labels: documentation

#833 Add check for expired GPG key
  Makefile.packaging
Labels: v3.x

#831 Update host metrics receiver
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/types.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/grafana/provisioning/dashboards/host-metrics.json
  test/mock/collector/nginx-agent.conf
  test/types/config.go
Labels: documentation, dependencies, chore, v3.x

#844 fix r30 pipeline failures
  .github/workflows/ci.yml
Labels: bug

#834 Add CLA bot workflow (#828)
  .github/workflows/f5-cla.yml
  CONTRIBUTING.md
Labels: documentation, v3.x

#835 Add README for NGINX OSS & Plus receivers
  internal/collector/nginxossreceiver/README.md
  internal/collector/nginxplusreceiver/README.md
Labels: documentation, v3.x

#838 Remove official docker images & move testing images to test folder
  .github/workflows/ci.yml
  Makefile
  examples/grafana-metrics/docker-compose.yml
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/Dockerfile.mainline
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/Dockerfile.stable
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/docker-compose.yml
  scripts/docker/official/nginx-oss-with-nginx-agent/alpine/entrypoint.sh
  scripts/docker/official/nginx-plus-with-nginx-agent/alpine/Dockerfile
  scripts/docker/official/nginx-plus-with-nginx-agent/alpine/docker-compose.yml
  scripts/docker/official/nginx-plus-with-nginx-agent/alpine/entrypoint.sh
  test/docker/agentless-entrypoint.sh
  test/docker/entrypoint.sh
  test/docker/nginx-official-image/apk/Dockerfile
  test/docker/nginx-official-image/deb/Dockerfile
  test/docker/nginx-oss/apk/Dockerfile
  test/docker/nginx-oss/deb/Dockerfile
  test/docker/nginx-oss/rpm/Dockerfile
  test/docker/nginx-plus/almalinux/Dockerfile
  test/docker/nginx-plus/alpine/Dockerfile
  test/docker/nginx-plus/amazonlinux/Dockerfile
  test/docker/nginx-plus/centos/Dockerfile
  test/docker/nginx-plus/debian/Dockerfile
  test/docker/nginx-plus/oraclelinux/Dockerfile
  test/docker/nginx-plus/redhatenterprise/Dockerfile
  test/docker/nginx-plus/rockylinux/Dockerfile
  test/docker/nginx-plus/suse/Dockerfile
  test/docker/nginx-plus/ubuntu/Dockerfile
  test/docker/performance/Dockerfile
  test/integration/api/docker-compose-official-image.yml
  test/integration/api/docker-compose.yml
  test/integration/features/docker-compose-official-image.yml
  test/integration/features/docker-compose.yml
  test/integration/grpc/docker-compose-official-image.yml
  test/integration/grpc/docker-compose.yml
  test/integration/install/docker-compose.yml
Labels: highlights, v2.x

#840 Avoid running config validation when file action fails
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
Labels: chore, v3.x

#836 Add exclude log to agent config
  internal/command/command_plugin_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/resource/nginx_log_tailer_operator.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  test/mock/collector/nginx-agent.conf
  test/types/config.go
Labels: chore, v3.x

#846 Add file watcher and data plane status update integration test
  internal/collector/nginxossreceiver/internal/metadata/generated_status.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
  test/config/nginx/nginx-with-server-block-access-log.conf
  test/integration/grpc_management_plane_api_test.go
Labels: chore, v3.x

#850 Update CODEOWNERS
  CODEOWNERS
Labels: chore, v3.x

#856 Set cache equal to false for setup-go github action
  .github/workflows/ci.yml
  .github/workflows/release-branch.yml
Labels: v3.x

#857 Fixed make target pointing at wrong Dockerfile and renamed others to be consistent
  Makefile
  test/docker/performance/Dockerfile
Labels: bug

#853 Check version command output
  .github/workflows/ci.yml
  test/integration/install/install_uninstall_test.go
Labels: chore, v2.x

#855 Move Dockerfiles to test
  Makefile
  internal/collector/nginxossreceiver/internal/metadata/generated_status.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
  test/docker/entrypoint.sh
  test/docker/nginx-official-image/apk/Dockerfile
  test/docker/nginx-official-image/deb/Dockerfile
  test/docker/nginx-oss/apk/Dockerfile
  test/docker/nginx-oss/deb/Dockerfile
  test/docker/nginx-oss/rpm/Dockerfile
  test/docker/nginx-plus/deb/Dockerfile
  test/helpers/test_containers_utils.go
Labels: chore

#863 Fix broken links causing deployment failures
  site/content/contribute/dev-environment-setup.md
  site/content/installation-upgrade/getting-started.md
Labels: bug, documentation

#864 Change connection created message log level
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_status.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_status.go
  internal/command/command_service.go
Labels: chore

#839 Update processors and exporters config for Otel collector
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  test/config/agent/nginx-agent-otel-load.conf
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/nginx-agent.conf
  test/types/config.go
Labels: chore, v3.x

#859 Added Integration tests to check install, uninstall of agent and version command
  Makefile
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  test/docker/agentless-entrypoint.sh
  test/helpers/test_containers_utils.go
  test/integration/install_uninstall_test.go
Labels: chore, v3.x

#867 Update building agent section in README
  README.md
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
Labels: documentation, chore, v3.x

#870 Fix collector extensions config
  internal/collector/otelcol.tmpl
  internal/config/config_test.go
  internal/config/types.go
  test/mock/collector/nginx-agent.conf
  test/types/config.go
Labels: bug, chore, v3.x

#868 Added default set of features to Agent Configuration
  docs/features/features.md
  internal/config/config.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/watcher/instance/instance_watcher_service.go
  nginx-agent.conf
  pkg/config/features.go
Labels: documentation, enhancement, chore, v3.x

#875 Update README.md
  README.md
Labels: documentation

#877 Temporarily stop publishing packages on v3 branch
  .github/workflows/ci.yml
  .github/workflows/release-branch.yml
Labels: v3.x
