Repository nginx/agent, pull requests merged in 2024-08, with the labels that each got.

#763 Add badges for Go version, release, license, contributions, and Slack…
  README.md
Labels: documentation

#764 Add badges to v3 for Go version, license, contributions, and Slack channel
  README.md
Labels: documentation

#739 Fix Post Install Script Issues
  .github/workflows/ci.yml
  Makefile.containers
  scripts/packages/nginx-agent.service
  scripts/packages/postinstall.sh
  scripts/packages/postremove.sh
  scripts/packages/postupgrade.sh
  scripts/packages/preremove.sh
Labels: bug, documentation, dependencies, chore

#755 Increase timeout period for collecting metrics
  src/core/metrics/sources/nginx_plus.go
  src/core/metrics/sources/nginx_plus_test.go
  src/core/nginx.go
  src/plugins/metrics.go
  src/plugins/metrics_throlling.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_throlling.go
Labels: dependencies, chore

#759 Add instructions for Amazon Linux 2023
  site/content/installation-upgrade/installation-oss.md
  site/content/installation-upgrade/installation-plus.md
  site/content/installation-upgrade/uninstall.md
Labels: documentation

#765 Add docs-build-push github workflow
  .github/workflows/docs-build-push.yml
  site/README.md
  site/netlify.toml
Labels: documentation

#770 docs: fix github links in changelog
  site/content/changelog.md
  site/go.mod
  site/go.sum
Labels: bug, documentation, dependencies

#771 Fix build packages workflow
  .github/workflows/build-package.yml
  api/grpc/mpi/v1/command_grpc.pb.go
  api/grpc/mpi/v1/files_grpc.pb.go
  api/grpc/mpi/v1/v1fakes/fake_command_service_client.go
Labels: bug, chore

#772 Remove file stats receiver
  go.mod
  go.sum
  internal/collector/factories.go
  internal/collector/factories_test.go
Labels: dependencies, chore

#773 Fix post install script for when no nginx instance is installed
  scripts/packages/postinstall.sh
Labels: bug

#766 Prevent writing outside allowed directories list from a config payload with actions
  Makefile
  docs/proto/proto.md
  sdk/proto/agent.pb.go
  sdk/proto/agent.proto
  src/core/config/types.go
  src/core/environment_test.go
  src/core/nginx.go
  src/plugins/registration.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/agent.pb.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/agent.proto
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/agent.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/agent.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/registration.go
  vendor/github.com/nginx/agent/sdk/v2/proto/agent.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/agent.proto
Labels: documentation, dependencies, chore

#776 docs: update GPG keys
  site/content/installation-upgrade/installation-oss.md
  site/content/installation-upgrade/installation-plus.md
Labels: documentation

#758 Only send NGINX config context updates if there is a change
  internal/logger/logger.go
  internal/model/config.go
  internal/model/config_test.go
  internal/resource/resource_plugin.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
Labels: chore, v3.x

#760 Add config apply integration test
  test/config/nginx/invalid-nginx.conf
  test/helpers/test_containers_utils.go
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/cmd/main.go
Labels: chore, v3.x

#781 Add manual Azure upload
  .github/workflows/azure-upload.yml
Labels: v2.x

#783 Change default log level to info
  internal/watcher/health/health_watcher_service.go
  nginx-agent.conf
Labels: chore, v3.x

#780 Update v3 release workflow
  .github/workflows/build-package.yml
  .github/workflows/release-branch.yml
  Makefile.packaging
Labels: v3.x

#756 Add new docker images to v2 pipeline for integration testing
  .github/workflows/ci.yml
  .github/workflows/release-branch.yml
  Makefile
  Makefile.containers
  test/docker/oss/apk/Dockerfile
  test/docker/oss/deb/Dockerfile
  test/integration/Dockerfile
  test/integration/api/api_test.go
  test/integration/api/docker-compose-official-image.yml
  test/integration/api/docker-compose-rpm.yml
  test/integration/api/docker-compose.yml
  test/integration/features/docker-compose-apk.yml
  test/integration/features/docker-compose-deb.yml
  test/integration/features/docker-compose-official-image.yml
  test/integration/features/docker-compose-rpm.yml
  test/integration/features/docker-compose.yml
  test/integration/grpc/docker-compose-deb.yml
  test/integration/grpc/docker-compose-official-image.yml
  test/integration/grpc/docker-compose-rpm.yml
  test/integration/grpc/docker-compose.yml
  test/integration/install/docker-compose-apk.yml
  test/integration/install/docker-compose-rpm.yml
  test/integration/install/docker-compose.yml
  test/integration/utils/test_container_utils.go
Labels: documentation, dependencies, chore, v2.x

#790 Update website changelog for v2.37.0
  site/content/changelog.md
Labels: documentation

#774 Pass on custom error log path at the time of validating config
  docs/proto/proto.md
  sdk/proto/nginx.pb.go
  sdk/proto/nginx.proto
  src/core/nginx.go
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/nginx.pb.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/proto/nginx.proto
  test/integration/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/integration/vendor/github.com/nginx/agent/v2/test/utils/nginx.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/nginx.pb.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/proto/nginx.proto
  test/performance/vendor/github.com/nginx/agent/v2/src/core/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/nginx.go
  test/utils/nginx.go
  vendor/github.com/nginx/agent/sdk/v2/proto/nginx.pb.go
  vendor/github.com/nginx/agent/sdk/v2/proto/nginx.proto
Labels: documentation, dependencies, chore, v2.x

#796 Fix broken URLS in docs
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/installation-upgrade/installation-oss.md
Labels: bug, documentation

#767 updating performance test to 1s
  sdk/backoff/backoff.go
  src/core/config/config.go
  src/core/environment.go
  src/core/metrics/aggregate_test.go
  src/core/os.go
  src/extensions/advanced_metrics.go
  src/extensions/advanced_metrics_test.go
  src/extensions/nap_monitoring.go
  src/extensions/nap_monitoring_test.go
  src/extensions/nginx-app-protect/nap/nap.go
  src/extensions/nginx_app_protect.go
  src/plugins/features_test.go
  src/plugins/file_watcher.go
  src/plugins/leak_test.go
  src/plugins/nginx_counter.go
  src/plugins/process_watcher_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/backoff/backoff.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/os.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/backoff/backoff.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/os.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/advanced_metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nap_monitoring.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx-app-protect/nap/nap.go
  test/performance/vendor/github.com/nginx/agent/v2/src/extensions/nginx_app_protect.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/file_watcher.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx_counter.go
  vendor/github.com/nginx/agent/sdk/v2/backoff/backoff.go
Labels: documentation, dependencies, chore, v2.x

#798 Fix link in config apply diagram
  docs/architecture/config_apply.md
Labels: bug, documentation, v3.x

#805 generated new docs for the payload
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
Labels: documentation, chore, v3.x

#795 Add MaxRecvMsgSize and MaxSendMsgSize to client and server options
  sdk/grpc/grpc.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
  vendor/github.com/nginx/agent/sdk/v2/grpc/grpc.go
Labels: dependencies, chore, v2.x

#797 Update docs-action workflow version
  .github/workflows/docs-build-push.yml
Labels: dependencies, v2.x

#799 Added MaxSendMsgSize and MaxRecvMsgSize to config
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_server.go
Labels: chore, v3.x

#792 Fix CorrelationID's for CreateConnection, UpdateDataPlaneStatus & UpdateOverview
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/command/commandfakes/fake_command_service.go
  internal/file/file_manager_service.go
  test/integration/grpc_management_plane_api_test.go
Labels: bug, chore, v3.x

#808 Update broken URL in installation-plus.md
  site/content/installation-upgrade/installation-plus.md
Labels: documentation, v2.x

#811 fix name of deprecated flag
  src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
Labels: bug, dependencies, chore

#815 (cherry-pick) Bump documentation theme version
  site/go.mod
  site/go.sum
Labels: dependencies

#807 added leak tests for agent v2
  src/core/payloads/register_software_details_test.go
  src/extensions/advanced-metrics/aggregator/leak_test.go
  src/extensions/advanced-metrics/ingester/leak_test.go
  src/extensions/advanced-metrics/pkg/advanced-metrics/advanced_metrics_test.go
  src/extensions/advanced-metrics/pkg/advanced-metrics/leak_test.go
  src/extensions/advanced-metrics/pkg/publisher/leak_test.go
  src/extensions/advanced-metrics/pkg/schema/leak_test.go
  src/extensions/advanced-metrics/pkg/schema/schema_builder_test.go
  src/extensions/advanced-metrics/reader/leak_test.go
  src/extensions/advanced-metrics/tables/leak_test.go
  src/extensions/advanced-metrics/tables/limits/leak_test.go
  src/extensions/advanced-metrics/tables/lookup/leak_test.go
  src/extensions/advanced-metrics/tables/priority_table/leak_test.go
  src/extensions/advanced-metrics/tables/sample/leak_test.go
  src/extensions/advanced-metrics/tables/schema/field_test.go
  src/extensions/advanced-metrics/tables/schema/leak_test.go
  src/extensions/advanced-metrics/tables/schema/schema_test.go
  src/extensions/leak_test.go
  src/extensions/nginx-app-protect/monitoring/manager/leak_test.go
  src/extensions/nginx-app-protect/monitoring/processor/leak_test.go
  src/extensions/nginx-app-protect/nap/leak_test.go
  src/extensions/prometheus-metrics/leak_test.go
Labels: chore, v2.x
