Repository nginx/agent, pull requests merged in 2024-12, with the labels that each got.

#933 removed validations from serial number
  Makefile
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  go.mod
  go.sum
  internal/datasource/cert/cert.go
  internal/file/file_manager_service_test.go
  internal/watcher/instance/nginx_config_parser_test.go
  pkg/files/file_helpers.go
  test/helpers/cert_utils.go
  test/mock/grpc/mock_management_file_service.go
  test/protos/files.go
Labels: documentation, dependencies, chore

#936 Fix race condition test
  go.mod
  go.sum
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  test/mock/grpc/mock_management_command_service.go
Labels: bug, dependencies, chore

#861 Add TLS configuration for the command server to the proto definitions
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/common.pb.validate.go
  api/grpc/mpi/v1/common.proto
  docs/proto/protos.md
  internal/config/mapper.go
  internal/config/mapper_test.go
  internal/watcher/instance/instance_watcher_service.go
Labels: documentation, dependencies, chore, v3.x

#938 Support unix socket to collect NGINX OSS and Plus metrics
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  go.mod
  go.sum
  internal/collector/nginxossreceiver/README.md
  internal/collector/nginxossreceiver/internal/config/config.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper_test.go
  internal/collector/nginxplusreceiver/README.md
  internal/collector/nginxplusreceiver/config.go
  internal/collector/nginxplusreceiver/factory.go
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/nginxplusreceiver/scraper_test.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/config_test.go
  internal/config/types.go
  internal/model/config.go
  internal/model/config_test.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/instance_watcher_service_test.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  internal/watcher/instance/nginx_process_parser.go
  internal/watcher/watcher_plugin.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/model/config.go
  test/protos/instances.go
Labels: documentation, dependencies, chore

#941 Add a docs page to explain NGINX Agent features
  site/content/configuration/configuration-overview.md
  site/content/configuration/configure-nginx-agent-features.md
Labels: documentation, enhancement

#943 Set the message identifiers as UUIDv7
  internal/collector/otel_collector_plugin_test.go
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/datasource/proto/message.go
  internal/datasource/proto/message_test.go
  internal/file/file_manager_service.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/logger/logger.go
  internal/resource/resource_plugin.go
  internal/watcher/file/file_watcher_service_test.go
  internal/watcher/instance/nginx_config_parser_test.go
  internal/watcher/watcher_plugin_test.go
  pkg/uuid/uuid.go
  test/helpers/os_utils.go
  test/helpers/os_utils_test.go
  test/helpers/slog_utils.go
  test/integration/install_uninstall_test.go
  test/mock/grpc/mock_management_command_service.go
  test/mock/grpc/mock_management_file_service.go
  test/protos/data_plane_response.go
Labels: chore

#946 Update the golang.org/x/crypto library to v0.31.0
  go.mod
  go.sum
Labels: dependencies, v3.x

#930 Added FileOverview to UpdateOverviewResponse
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
  internal/logger/logger.go
Labels: documentation, chore, v3.x

#944 Change serial number from bytes to string
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/file/file_manager_service_test.go
  pkg/files/file_helpers.go
  test/protos/files.go
Labels: documentation, chore, v3.x

#951 Added API Action Request
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/bus/topics.go
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/resource/resourcefakes/fake_resource_service_interface.go
  pkg/config/features.go
  test/helpers/nginx_plus.go
  test/protos/management_plane_request.go
Labels: documentation, chore

#953 Updated golang.org/x/net version
  go.mod
  go.sum
Labels: dependencies, v3.x

#932 Add OTel tcplog receiver for NAP
  go.mod
  go.sum
  internal/collector/factories.go
  internal/collector/factories_test.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/defaults.go
  internal/config/types.go
  internal/model/config.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/config/nginx/nginx-with-multiple-access-logs.conf
  test/mock/collector/otel-collector.yaml
  test/model/config.go
Labels: enhancement, dependencies, chore, v3.x

#940 Updates NAP receivers when NAP directives are deleted
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/config/types.go
Labels: chore, v3.x
