Repository nginx/agent, pull requests merged in 2024-06, with the labels that each got.

#700 Fix metrics reporter retry logic
  sdk/client/metric_reporter.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Labels: bug, dependencies, chore

#682 Add Ubuntu Noble 24.04 LTS support
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/label-pr.yml
  .github/workflows/scorecards.yml
  Makefile
  Makefile.packaging
  scripts/docker/nginx-oss/deb/Dockerfile
  scripts/docker/nginx-plus/debian/Dockerfile
  scripts/docker/nginx-plus/ubuntu/Dockerfile
  scripts/packages/postinstall.sh
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/technical-specifications.md
  test/docker/Dockerfile
  test/integration/Dockerfile
  test/integration/install/install_uninstall_test.go
Labels: documentation, chore

#703 Add pkg folder for external code utilization
  Makefile
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  docs/architecture/layout.md
  go.mod
  internal/command/command_plugin_test.go
  internal/command/command_service_test.go
  internal/config/config.go
  internal/file/file_manager_service.go
  internal/service/config/nginx_config_service.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  internal/watcher/instance/nginx_process_parser.go
  pkg/files/file_helpers.go
  pkg/files/file_helpers_test.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
  test/mock/grpc/mock_management_file_service.go
  test/protos/management_plane_request.go
  test/stub/logger.go
Labels: documentation, dependencies, chore

#698 feat: create OTel collector config from template
  .gitignore
  go.mod
  go.sum
  internal/app.go
  internal/collector/build.go
  internal/collector/build_test.go
  internal/collector/factories.go
  internal/collector/factories_test.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings.go
  internal/collector/settings_test.go
  internal/command/command_plugin_test.go
  internal/command/command_service_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/datasource/config/config_writer_test.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin_test.go
  internal/grpc/grpc_test.go
  internal/metrics/collector/config_test.go
  internal/metrics/collector/otel_collector_plugin_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/service/config/nginx_config_service_benchmark_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service_test.go
  internal/watcher/health/health_watcher_service_test.go
  internal/watcher/instance/instance_watcher_service_test.go
  internal/watcher/instance/nginx_config_parser_benchmark_test.go
  internal/watcher/instance/nginx_config_parser_test.go
  internal/watcher/watcher_plugin_test.go
  nginx-agent.conf
  test/config/collector/test-otelcol.yaml
  test/mock/grpc/cmd/main.go
  test/types/config.go
Labels: enhancement, dependencies, chore

#708 R32 operating system support parity
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  site/content/technical-specifications.md
Labels: documentation, highlights

#706 Change environment prefix from nms to nginx_agent
  main.go
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/config/defaults.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
Labels: bug, dependencies, chore

#710 Update environment variables from NMS to NGINX_AGENT
  site/content/configuration/configuration-overview.md
  site/content/configuration/encrypt-communication.md
Labels: documentation

#712 Update the flag & environment table callouts
  site/content/configuration/configuration-overview.md
Labels: documentation

#716 fix: add deduplication for the same ssl cert metadata
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug, dependencies, chore

#724 Fix release workflow
  .github/workflows/release-branch.yml
  Makefile.packaging
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: bug, dependencies, chore

#715 Fix incorrect bold tag in heading
  site/content/configuration/encrypt-communication.md
Labels: bug, documentation

#702 Upload nginx config
  internal/bus/topics.go
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/command/commandfakes/fake_command_service.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  nginx-agent.conf
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/mock_management_command_service.go
  test/protos/data_plane_response.go
Labels: chore

#720 URL fix for building docker image in README.md
  README.md
Labels: bug, documentation

#719 Fix check for comparing children PIDs
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/instance_watcher_service_test.go
Labels: bug, chore

#725 Increase health watcher test coverage
  internal/watcher/health/health_watcher_service_test.go
  test/protos/instances.go
Labels: chore

#726 Remove unused code
  Makefile
  api/grpc/buf.yaml
  api/grpc/instances/configurations.pb.go
  api/grpc/instances/configurations.proto
  internal/bus/topics.go
  internal/client/clientfakes/fake_config_client.go
  internal/client/config_client.go
  internal/datasource/config/cache.go
  internal/datasource/config/cache_test.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/datasource/config/configfakes/fake_file_cache_interface.go
  internal/datasource/nginx/nginx_process.go
  internal/datasource/nginx/nginx_process_test.go
  internal/model/config.go
  internal/model/instance.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/config/data_plane_config_service.go
  internal/service/config/data_plane_config_service_test.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_config_service_benchmark_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/servicefakes/fake_config_service_interface.go
  internal/watcher/instance/nginx_config_parser_benchmark_test.go
  test/protos/instances.go
Labels: chore
