Repository nginx/agent, pull requests merged in 2024-04, with the labels that each got.

#624 Add correlation id to context
  internal/bus/fake_message_pipe.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/client/http_config_client.go
  internal/datasource/config/cache.go
  internal/datasource/config/cache_test.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/datasource/config/configfakes/fake_file_cache_interface.go
  internal/datasource/host/exec/exec.go
  internal/datasource/host/exec/exec_test.go
  internal/datasource/host/exec/execfakes/fake_exec_interface.go
  internal/datasource/host/process.go
  internal/datasource/nginx/log_tailer.go
  internal/datasource/nginx/nginx_process.go
  internal/datasource/nginx/nginx_process_test.go
  internal/logger/logger.go
  internal/logger/logger_test.go
  internal/model/instance.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/instance_plugin.go
  internal/plugin/instance_plugin_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/process_monitor_plugin.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/config/data_plane_config_service.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_config_service_benchmark_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config/nginx_gateway_fabric_config_service.go
  internal/service/config/nginx_gateway_fabric_config_service_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/instance/data_plane_instance_service.go
  internal/service/instance/instancefakes/fake_data_plane_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service_test.go
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_benchmark_test.go
  internal/service/instance/nginx_instance_service_test.go
  internal/service/instance_service.go
  internal/service/instance_service_test.go
  internal/service/servicefakes/fake_config_service_interface.go
  internal/service/servicefakes/fake_instance_service_interface.go
  test/mock/http/mock_management_plane_server.go
Labels: chore

#623 Compare performance test results
  .github/workflows/ci.yml
  api/grpc/instances/configurations.pb.go
  api/grpc/instances/file.pb.go
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command_grpc.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files_grpc.pb.go
Labels: documentation, chore

#618 Add client health check, retry for dial context and retry for create connection rpc
  go.mod
  go.sum
  internal/backoff/backoff.go
  internal/backoff/backoff_test.go
  internal/bus/topics.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/grpc/certificates.go
  internal/grpc/certificates_test.go
  internal/grpc/credentials.go
  internal/grpc/credentials_test.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/metrics/export/otel.go
  internal/metrics/export/otel_test.go
  internal/metrics/source/prometheus/prometheus.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/process_monitor_plugin.go
  test/helpers/cert_utils.go
  test/helpers/test_containers_utils.go
  test/integration/data_plane_api_test.go
  test/integration/grpc_connection_test.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_command_service.go
  test/mock/grpc/mock_management_file_service.go
  test/mock/grpc/mock_management_server.go
  test/types/config.go
Labels: dependencies, chore

#630 Update protos used in config apply
  api/grpc/buf.yaml
  api/grpc/instances/file.pb.go
  api/grpc/instances/file.proto
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/client/clientfakes/fake_config_client_interface.go
  internal/client/http_config_client.go
  internal/client/http_config_client_test.go
  internal/datasource/config/cache.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/datasource/config/configfakes/fake_file_cache_interface.go
  internal/plugin/config_plugin_test.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/servicefakes/fake_config_service_interface.go
  test/helpers/os_utils.go
  test/protos/instances.go
Labels: documentation, chore

#628 Send data plane status update request
  api/grpc/instances/configurations.pb.go
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command_grpc.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files_grpc.pb.go
  api/grpc/mpi/v1/mocks.go
  api/grpc/mpi/v1/v1fakes/fake_command_service_client.go
  api/grpc/mpi/v1/v1fakes/fake_file_service_client.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/instance_plugin.go
  internal/plugin/instance_plugin_test.go
  internal/plugin/process_monitor_plugin.go
  internal/plugin/process_monitor_plugin_test.go
  test/helpers/test_containers_utils.go
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_command_service.go
  test/mock/grpc/mock_management_server.go
Labels: chore

#631 Fix send data plane status update nil pointer exception
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
Labels: bug, chore

#632 Upgrade go version to 1.22
  .golangci.yml
  Makefile.tools
  api/grpc/mpi/v1/mocks.go
  api/http/dataplane/client.gen.go
  api/http/dataplane/data_plane.gen.go
  go.mod
  go.sum
  internal/client/http_config_client.go
  internal/config/config.go
  internal/datasource/config/cache.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/host/exec/exec.go
  internal/metrics/export/otel_test.go
  internal/metrics/source/prometheus/convert_test.go
  internal/metrics/source/prometheus/prometheus_test_data.txt
  internal/model/metrics.go
  internal/plugin/metrics_plugin.go
  internal/plugin/process_monitor_plugin.go
  internal/service/config/data_plane_config_service.go
  internal/service/config/nginx_config_service.go
  internal/service/config_service.go
  internal/service/instance/data_plane_instance_service.go
  internal/service/instance_service.go
  scripts/packages/packager/Dockerfile
  site/content/installation-upgrade/getting-started.md
  site/content/previous-versions/NGINX-agent-v2/installation-upgrade/getting-started.md
  test/helpers/go_utils.go
  test/helpers/go_utils_test.go
  test/integration/data_plane_api_test.go
  test/mock/grpc/mock_management_file_service.go
  test/mock/grpc/mock_management_server.go
  test/mock/http/mock_management_plane.gen.go
  test/mock/http/mock_management_plane_server.go
Labels: documentation, dependencies, chore

#633 Add uuid and rename token to authorization header for gRPC connections
  internal/config/config.go
  internal/config/config_test.go
  internal/config/flags.go
  internal/config/types.go
  internal/grpc/credentials.go
  internal/grpc/credentials_test.go
  internal/grpc/grpc.go
  internal/plugin/grpc_client_plugin.go
Labels: chore

#634 Add resource to create connection request
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  go.mod
  internal/datasource/host/exec/exec.go
  internal/datasource/host/exec/execfakes/fake_exec_interface.go
  internal/datasource/host/hostfakes/fake_info_interface.go
  internal/datasource/host/info.go
  internal/datasource/host/info_test.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/service/resource_service.go
  internal/service/resource_service_test.go
  internal/service/servicefakes/fake_resource_service_interface.go
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/mock_management_command_service.go
Labels: documentation, dependencies, chore

#635 Add public files package
  Makefile
  files/file_helpers.go
  files/file_helpers_test.go
  internal/datasource/host/file_helpers.go
  internal/datasource/host/file_helpers_test.go
  internal/service/config/nginx_config_service.go
  test/mock/grpc/mock_management_file_service.go
Labels: chore

#638 Add UpdateDataPlaneHealth RPC to mock management plane
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  test/mock/grpc/mock_management_command_service.go
Labels: documentation, chore

#643 added missing context to log statements
  cmd/agent/main.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_command_service.go
Labels: chore

#642 Added Agent instance to resource payload
  internal/plugin/plugin_manager.go
  internal/plugin/resource_plugin.go
  internal/plugin/resource_plugin_test.go
  internal/service/config/nginx_config_service.go
  internal/service/instance/agent_instance_service.go
  internal/service/instance/agent_instance_service_test.go
  internal/service/instance_service.go
  internal/service/instance_service_test.go
  test/integration/grpc_management_plane_api_test.go
  test/types/config.go
Labels: chore

#644 Add unary client interceptor for proto validation
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  api/grpc/buf.gen.yaml
  api/grpc/buf.lock
  api/grpc/buf.yaml
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command_grpc.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/common.pb.validate.go
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files_grpc.pb.go
  docs/proto/protos.md
  go.mod
  go.sum
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  test/helpers/test_containers_utils.go
  test/mock/grpc/Dockerfile
  test/mock/grpc/mock_management_server.go
Labels: documentation, dependencies, chore

#640 Add gRPC config client, file service client & updated mock management plane
  Makefile
  api/grpc/instances/configurations.pb.go
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  files/file_helpers.go
  files/file_helpers_test.go
  internal/bus/topics.go
  internal/client/clientfakes/fake_config_client.go
  internal/client/clientfakes/fake_config_client_interface.go
  internal/client/config_client.go
  internal/client/http_config_client.go
  internal/client/http_config_client_test.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/config/data_plane_config_service.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_config_service_benchmark_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config/nginx_gateway_fabric_config_service.go
  internal/service/config/nginx_gateway_fabric_config_service_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/servicefakes/fake_config_service_interface.go
  test/config/nginx/nginx.conf
  test/helpers/id_generator_utils.go
  test/helpers/test_containers_utils.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_command_service.go
  test/mock/grpc/mock_management_file_service.go
  test/mock/grpc/mock_management_server.go
  test/protos/common.go
  test/protos/config.go
  test/protos/files.go
  test/protos/instances.go
  test/protos/management_plane_request.go
Labels: documentation, chore

#646 Add proto validation rules to messages
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/common.proto
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/grpc/grpc_test.go
Labels: documentation, chore

#647 Stop grpc retry if an invalid argument error is found
  internal/grpc/grpc_test.go
  internal/plugin/grpc_client_plugin.go
Labels: chore

#649 Handle context done in mock management plane subscribe function
  internal/bus/topics.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  test/mock/grpc/mock_management_command_service.go
Labels: chore

#653 Change go.mod version from v1.22.2 to v1.22
  .github/workflows/ci.yml
  go.mod
Labels: dependencies

#648 Add LoadableModules to NGINX Info
  internal/grpc/grpc_test.go
  internal/plugin/config_plugin_test.go
  internal/service/config/data_plane_config_service_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service_test.go
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_test.go
  internal/service/instance_service_test.go
  test/protos/config.go
  test/protos/instances.go
  test/protos/resource.go
Labels: chore

#657 Bump the version of github.com/opencontainers/runc dependency
  go.work.sum
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/github.com/moby/sys/user/LICENSE
  test/integration/vendor/github.com/moby/sys/user/lookup_unix.go
  test/integration/vendor/github.com/moby/sys/user/user.go
  test/integration/vendor/github.com/moby/sys/user/user_fuzzer.go
  test/integration/vendor/github.com/opencontainers/runc/NOTICE
  test/integration/vendor/github.com/opencontainers/runc/libcontainer/user/lookup_deprecated.go
  test/integration/vendor/github.com/opencontainers/runc/libcontainer/user/user_deprecated.go
  test/integration/vendor/modules.txt
Labels: dependencies, chore

#658 Send resource id as id in rpc dial options
  go.mod
  internal/app.go
  internal/datasource/host/hostfakes/fake_info_interface.go
  internal/datasource/host/info.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/plugin/grpc_client_plugin.go
Labels: dependencies, chore
