Repository nginx/agent, pull requests merged in 2024-10, with the labels that each got.

#869 Docs: Add hugo version check and theme update to Makefile
  site/README.md
  site/go.mod
  site/go.sum
  site/go.work
  site/hugo-entrypoint.sh
  site/makefile
Labels: documentation, dependencies, v2.x

#883 Add hugo version check and theme update to Makefile
  site/go.mod
  site/go.sum
  site/hugo-entrypoint.sh
  site/makefile
Labels: dependencies

#885 Fix oss tests
  .github/workflows/ci.yml
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
Labels: bug, chore

#876 Update PGO Profile
  .github/workflows/ci.yml
  default.pgo
Labels: chore, v3.x

#881 Fix APK package names
  Makefile.packaging
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
Labels: bug, chore, v3.x

#887 Update mdatagen install instructions in README.md
  README.md
Labels: documentation, v3.x

#888 Fix NGINX OSS integration tests
  .github/workflows/ci.yml
Labels: bug, v2.x

#884 Change casing of docs makefile to Makefile
  site/Makefile
Labels: documentation, v2.x

#886 docs: enableGitInfo config and docs-action bump
  .github/workflows/docs-build-push.yml
  site/config/_default/config.toml
Labels: documentation, v2.x

#865 Update go version to 1.23
  .golangci.yml
  Makefile.tools
  go.mod
  go.sum
  internal/bus/message_pipe_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/grok_test.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper_test.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/resource/nginx_instance_operator_test.go
  internal/resource/nginx_log_tailer_operator.go
  internal/resource/nginx_log_tailer_operator_test.go
  internal/watcher/instance/nginx_config_parser_test.go
  internal/watcher/instance/nginx_process_parser.go
  scripts/packages/packager/Dockerfile
  site/content/installation-upgrade/getting-started.md
  site/content/previous-versions/NGINX-agent-v2/installation-upgrade/getting-started.md
  test/helpers/go_utils_test.go
  test/helpers/nginx_plus.go
  test/helpers/os_utils.go
  test/integration/install_uninstall_test.go
Labels: documentation, dependencies, chore, v3.x

#882 Agent Config Changes: rename & update config_dirs & update exclude_logs
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  nginx-agent.conf
  scripts/packages/postinstall.sh
  test/config/agent/nginx-agent-otel-load.conf
  test/config/agent/nginx-config-with-grpc-client.conf
  test/mock/collector/nginx-agent.conf
  test/types/config.go
Labels: chore

#880 Use Max NGINX Plus API version
  go.mod
  go.sum
  internal/collector/nginxplusreceiver/scraper.go
Labels: dependencies, chore, v3.x

#893 Log error from integration test
  test/integration/grpc_management_plane_api_test.go
Labels: chore

#892 Fix docs docker failing without git context
  site/config/docker/config.toml
  site/go.mod
  site/go.sum
  site/hugo-entrypoint.sh
Labels: bug, documentation, dependencies, v2.x

#896 [Cherry pick] Fix docs docker failing without git context
  site/config/docker/config.toml
  site/go.mod
  site/go.sum
  site/hugo-entrypoint.sh
Labels: bug, dependencies

#897 Remove link to github dockerfiles
  site/content/installation-upgrade/container-environments/docker-images.md
Labels: documentation

#898 Docs: Update link to 3rd party site
  README.md
  site/content/installation-upgrade/getting-started.md
Labels: documentation

#872 Add default config for command
  docs/features/features.md
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/command/command_service.go
  internal/command/commandfakes/fake_command_service.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/types.go
  internal/datasource/host/info.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/watcher/watcher_plugin.go
  test/types/config.go
Labels: documentation, chore, v3.x

#903 Enabling publishing packages
  .github/workflows/ci.yml
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
Labels: chore

#900 Improve comments for docs, make private objects public
  pkg/tls/self_signed_cert.go
Labels: chore

#878 OpenTelemetry: add resource id
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/config/config.go
  internal/config/flags.go
  internal/config/types.go
Labels: documentation, dependencies, chore, v3.x

#905 Add header_setter extension for OTel collector
  Makefile
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/config_test.go
  internal/config/types.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/docker-compose.yaml
  test/mock/collector/mock-collector/Dockerfile
  test/mock/collector/mock-collector/auth/auth.go
  test/mock/collector/mock-collector/auth/config.go
  test/mock/collector/mock-collector/go.mod
  test/mock/collector/mock-collector/go.sum
  test/mock/collector/mock-collector/main.go
  test/mock/collector/nginx-agent.conf
  test/mock/collector/otel-collector.yaml
  test/types/config.go
Labels: dependencies, chore

#907 Allowlist Error Messages
  src/plugins/nginx.go
  src/plugins/nginx_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
Labels: dependencies, chore

#908 OpenTelemetry: Add nginx instance id and instance type
  go.mod
  internal/collector/nginxossreceiver/documentation.md
  internal/collector/nginxossreceiver/internal/config/config.go
  internal/collector/nginxossreceiver/internal/metadata/generated_config.go
  internal/collector/nginxossreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_resource.go
  internal/collector/nginxossreceiver/internal/metadata/generated_resource_test.go
  internal/collector/nginxossreceiver/internal/metadata/testdata/config.yaml
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/testdata/expected.yaml
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper_test.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/testdata/expected.yaml
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/testdata/expected_with_connections_as_gauge.yaml
  internal/collector/nginxossreceiver/metadata.yaml
  internal/collector/nginxossreceiver/testdata/integration/expected.yaml
  internal/collector/nginxplusreceiver/config.go
  internal/collector/nginxplusreceiver/documentation.md
  internal/collector/nginxplusreceiver/internal/metadata/generated_config.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_resource.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_resource_test.go
  internal/collector/nginxplusreceiver/internal/metadata/testdata/config.yaml
  internal/collector/nginxplusreceiver/metadata.yaml
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/nginxplusreceiver/scraper_test.go
  internal/collector/nginxplusreceiver/testdata/expected.yaml
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/config/types.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/otel-collector.yaml
Labels: documentation, dependencies, chore
