Repository nginx/agent, pull requests merged in 2024-07, with the labels that each got.

#727 Change file hash
  Makefile
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_benchmark_test.go
  internal/watcher/instance/nginx_config_parser_test.go
  pkg/files/file_helpers.go
  pkg/files/file_helpers_test.go
  test/helpers/config_utils.go
  test/mock/grpc/mock_management_file_service.go
Labels: chore

#731 Update configuration examples
  site/content/configuration/configuration-overview.md
Labels: documentation

#732 Fix for version
  Makefile
Labels: bug

#733 Added field alignment ordering, enabled static code analysis
  .golangci.yml
  internal/backoff/backoff_test.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/collector/otel_collector_plugin.go
  internal/command/command_service.go
  internal/config/config_test.go
  internal/config/types.go
  internal/datasource/host/info.go
  internal/datasource/host/info_test.go
  internal/file/file_plugin_test.go
  internal/grpc/grpc_test.go
  internal/logger/logger_test.go
  internal/model/config.go
  internal/model/os.go
  internal/resource/nginx_instance_operator_test.go
  internal/resource/nginx_log_tailer_operator_test.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/watcher/health/health_watcher_service_test.go
  internal/watcher/health/nginx_health_watcher_operator_test.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/instance_watcher_service_test.go
  internal/watcher/instance/nginx_config_parser_test.go
  internal/watcher/instance/nginx_process_parser.go
  internal/watcher/instance/nginx_process_parser_test.go
  pkg/files/file_helpers_test.go
  test/load/nginx_agent_process_collector.go
  test/mock/grpc/mock_management_command_service.go
  test/mock/grpc/mock_management_file_service.go
Labels: chore

#734 Agent version
  internal/app.go
Labels: chore

#735 updated github.com/rs/cors version
  go.mod
  go.sum
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/rs/cors/README.md
  test/performance/vendor/github.com/rs/cors/cors.go
  test/performance/vendor/github.com/rs/cors/internal/sortedset.go
  test/performance/vendor/github.com/rs/cors/utils.go
  test/performance/vendor/modules.txt
  vendor/github.com/rs/cors/README.md
  vendor/github.com/rs/cors/cors.go
  vendor/github.com/rs/cors/internal/sortedset.go
  vendor/github.com/rs/cors/utils.go
  vendor/modules.txt
Labels: documentation, dependencies, chore

#736 docs: update changelog
  site/content/changelog.md
Labels: documentation

#738 upgrade crossplane
  go.mod
  go.sum
  lefthook.yml
Labels: dependencies

#741 Add correlation id to update file request
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/file/file_manager_service.go
Labels: documentation, dependencies, chore

#730 Update Data Plane Response Statuses & Clean Up
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
  internal/model/config.go
  internal/resource/nginx_instance_operator.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/watcher/watcher_plugin.go
Labels: chore

#744 Add DetermineFileAction Function
  pkg/files/file_helpers.go
  pkg/files/file_helpers_test.go
Labels: chore

#746 Upgrade crossplane version to prevent Agent from rolling back in the case of valid NGINX configurations
  go.mod
  go.sum
  go.work.sum
  sdk/go.mod
  sdk/go.sum
  sdk/vendor/github.com/nginxinc/nginx-go-crossplane/README.md
  sdk/vendor/github.com/nginxinc/nginx-go-crossplane/analyze_nplus_latest_directives.go
  sdk/vendor/modules.txt
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/README.md
  test/integration/vendor/github.com/nginxinc/nginx-go-crossplane/analyze_nplus_latest_directives.go
  test/integration/vendor/modules.txt
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/README.md
  test/performance/vendor/github.com/nginxinc/nginx-go-crossplane/analyze_nplus_latest_directives.go
  test/performance/vendor/modules.txt
  vendor/github.com/nginxinc/nginx-go-crossplane/README.md
  vendor/github.com/nginxinc/nginx-go-crossplane/analyze_nplus_latest_directives.go
  vendor/modules.txt
Labels: bug, documentation, dependencies, chore, highlights

#743 Fix data plane response messages and errors
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  test/mock/grpc/mock_management_file_service.go
Labels: bug, chore

#747 Added version regex to parse the logs to see if matches vsemvar format
  test/integration/utils/test_container_utils.go
Labels: chore

#753 feat: Update the changelog
  site/content/changelog.md
Labels: documentation, enhancement

#745 Update ConfigApplyRequest and ConfigUploadRequest protos
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  test/protos/management_plane_request.go
Labels: documentation, chore

#751 The letter v is now always prepended to output of -v
  .github/workflows/release-branch.yml
  Makefile
  Makefile.packaging
  scripts/packages/packager/local-entrypoint.sh
  scripts/packages/packager/signed-entrypoint.sh
Labels: bug

#754 Mock management plane refactor
  internal/watcher/instance/instance_watcher_service.go
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_command_service.go
  test/mock/grpc/mock_management_file_service.go
  test/mock/grpc/mock_management_server.go
Labels: chore

#750 Config Apply Diagrams
  Makefile
  docs/architecture/README.md
  docs/architecture/config_apply.md
  docs/architecture/config_apply_rollback.md
  docs/architecture/config_apply_state.md
Labels: documentation

#752 Fix backoff to drop Metrics Reports from buffer after max_elapsed_time has been reached
  site/content/configuration/configuration-overview.md
  src/core/config/config.go
  src/core/config/config_test.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/core/grpc.go
  src/plugins/testdata/configs/updated.conf
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/grpc.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/grpc.go
Labels: bug, documentation, dependencies, chore

#761 update docker version
  test/integration/go.mod
  test/integration/vendor/modules.txt
Labels: dependencies
