Repository nginx/agent, pull requests merged in 2024-11, with the labels that each got.

#911 Add UUID header OTel collector
  Makefile
  go.mod
  internal/collector/nginxossreceiver/internal/metadata/generated_resource_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_resource_test.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/config/config.go
  internal/config/flags.go
  test/mock/collector/mock-collector/Dockerfile
  test/mock/collector/mock-collector/auth/auth.go
  test/mock/collector/mock-collector/auth/config.go
  test/mock/collector/mock-collector/go.mod
  test/mock/collector/mock-collector/go.sum
  test/mock/collector/mock-collector/main.go
  test/mock/collector/otel-collector.yaml
  test/types/config.go
Labels: dependencies, chore

#910 Add support for Management Plane Health Request
  internal/bus/topics.go
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/watcher/health/health_watcher_service.go
  internal/watcher/health/health_watcher_service_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
  test/integration/grpc_management_plane_api_test.go
Labels: chore, v3.x

#909 Allowlist Error Messages
  Makefile
  internal/resource/nginx_instance_operator.go
  internal/resource/nginx_log_tailer_operator.go
  internal/resource/nginx_log_tailer_operator_test.go
Labels: chore

#912 Config Apply - Determine File Diff
  internal/bus/topics.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
  pkg/files/file_helpers.go
  pkg/files/file_helpers_test.go
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/mock_management_command_service.go
  test/protos/files.go
Labels: chore

#914 Update config apply diagrams
  docs/architecture/config_apply.md
  docs/architecture/config_apply_rollback.md
Labels: documentation, v3.x

#915 Add more detail to subject and issuer
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/file/file_manager_service_test.go
  test/protos/files.go
Labels: documentation, chore, v3.x

#921 Add check that integration tests pass before making a release
  .github/workflows/ci.yml
Labels: v3.x

#916 Add support for Agent connection to mpi regardless of NGINX Instance status
  internal/command/command_service.go
  internal/command/command_service_test.go
  test/docker/nginxless-entrypoint.sh
  test/helpers/test_containers_utils.go
  test/integration/grpc_management_plane_api_test.go
  test/integration/nginx_less_mpi_connection_test.go
Labels: enhancement, v3.x

#922 Fail release job if packages fail to publish.
  Makefile.packaging
Labels: chore, v3.x

#917 Otel fix missing attributes
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/otel_collector_plugin_test.go
Labels: bug, chore, v3.x

#919 Add hostname to ContainerInfo
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/command/command_service.go
  internal/datasource/host/hostfakes/fake_info_interface.go
  internal/datasource/host/info.go
  internal/datasource/host/info_test.go
  internal/resource/resource_service.go
Labels: documentation, enhancement, chore, v3.x

#927 Docs: updating links from /nginx-management-suite/nim to /nginx-instance-manager
  README.md
  site/content/configuration/encrypt-communication.md
  site/content/overview.md
Labels: documentation

#928 docs: Fix NGINX install link and dockerfile section
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/installation-upgrade/getting-started.md
  site/go.mod
  site/go.sum
Labels: bug, documentation, dependencies

#925 Update regex for monitoring error logs
  internal/resource/nginx_log_tailer_operator.go
  internal/resource/nginx_log_tailer_operator_test.go
Labels: chore, v3.x

#924 Autodeploy main docs to production
  .github/workflows/docs-build-push.yml
Labels: documentation

#923 Fail release job if packages fail to publish
  Makefile.packaging
Labels: chore, v2.x

#937 Update performance test Dockerfile to use NGINX R32
  test/docker/performance/Dockerfile
Labels: chore

#935 update otel collector version
  README.md
  go.mod
  go.sum
  internal/collector/factories.go
  internal/collector/factories_test.go
  internal/collector/nginxossreceiver/factory.go
  internal/collector/nginxossreceiver/factory_test.go
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_resource_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/config.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/input.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/input_test.go
  internal/collector/nginxplusreceiver/factory.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_resource_test.go
Labels: documentation, dependencies, chore
