Repository nginx/agent, pull requests merged in 2024-05, with the labels that each got.

#654 Add dynamic modules to NGINX Info
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_test.go
  test/protos/instances.go
Labels: chore

#662 feat: add management plane connect doc
  site/content/configuration/connect-management-plane.md
Labels: documentation, enhancement

#661 Fix NGINX Plus Instance, NGINX Version
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_test.go
  test/protos/instances.go
Labels: bug, chore

#663 Increase plugin test coverage
  internal/plugin/grpc_client_plugin_test.go
Labels: chore

#660 Change GetProcesses to only return nginx processes & fix get Instances
  internal/datasource/host/process.go
  internal/datasource/host/process_benchmark_test.go
  internal/datasource/host/process_test.go
  internal/plugin/process_monitor_plugin.go
  internal/plugin/process_monitor_plugin_test.go
  internal/plugin/resource_plugin.go
  internal/plugin/resource_plugin_test.go
  internal/service/instance/agent_instance_service.go
  internal/service/instance/agent_instance_service_test.go
  internal/service/instance/data_plane_instance_service.go
  internal/service/instance/instancefakes/fake_data_plane_instance_service.go
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_benchmark_test.go
  internal/service/instance/nginx_instance_service_test.go
  internal/service/instance_service.go
  internal/service/instance_service_test.go
  internal/service/servicefakes/fake_instance_service_interface.go
Labels: bug, chore

#665 Add health check endpoint
  .github/workflows/ci.yml
  docs/swagger.json
  main.go
  sdk/client/client.go
  sdk/client/commander.go
  sdk/client/controller.go
  sdk/client/controller_test.go
  sdk/client/metric_reporter.go
  src/core/topics.go
  src/plugins/agent_api.go
  src/plugins/agent_api_test.go
  src/plugins/commander.go
  src/plugins/commander_test.go
  src/plugins/metrics.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  src/plugins/metrics_test.go
  src/plugins/registration.go
  src/plugins/registration_test.go
  test/component/nginx-app-protect/monitoring/monitoring_test.go
  test/integration/features/features_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/client.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/controller.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/integration/vendor/github.com/nginx/agent/v2/test/utils/agent_config.go
  test/performance/metrics_test.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/client.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/controller.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/topics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/registration.go
  test/performance/vendor/github.com/nginx/agent/v2/test/utils/agent_config.go
  test/utils/agent_config.go
  vendor/github.com/nginx/agent/sdk/v2/client/client.go
  vendor/github.com/nginx/agent/sdk/v2/client/commander.go
  vendor/github.com/nginx/agent/sdk/v2/client/controller.go
  vendor/github.com/nginx/agent/sdk/v2/client/metric_reporter.go
Labels: dependencies, chore

#668 Remove unnecessary freebsd logic for finding process executable
  src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
Labels: dependencies, chore

#671 Add additional checks in chunking functionality
  sdk/checksum/checksum.go
  sdk/checksum/checksum_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/checksum/checksum.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/checksum/checksum.go
  vendor/github.com/nginx/agent/sdk/v2/checksum/checksum.go
Labels: dependencies, chore

#676 Fix oracle linux integration test
  scripts/docker/nginx-oss/rpm/Dockerfile
Labels: bug

#678 fix: fix title case in v3 branch
  site/content/_index.md
  site/content/configuration/configuration-overview.md
  site/content/configuration/configure-nginx-agent-group.md
  site/content/configuration/encrypt-communication.md
  site/content/contribute/community.md
  site/content/contribute/dev-environment-setup.md
  site/content/installation-upgrade/_index.md
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/installation-upgrade/container-environments/docker-support.md
  site/content/installation-upgrade/getting-started.md
  site/content/installation-upgrade/installation-github.md
  site/content/installation-upgrade/installation-oss.md
  site/content/installation-upgrade/installation-plus.md
  site/content/installation-upgrade/uninstall.md
  site/content/installation-upgrade/upgrade.md
  site/content/technical-specifications.md
Labels: bug, documentation

#679 Add ConfigUploadRequest proto definition
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  docs/proto/protos.md
Labels: documentation, chore

#677 Refactor resource plugin
  internal/bus/topics.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/resource/resourcefakes/fake_resource_service_interface.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
Labels: chore

#683 Send data plane health request
  internal/bus/topics.go
  internal/config/config.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/watcher/health_watcher_service.go
  internal/watcher/health_watcher_service_test.go
  internal/watcher/nginx_health_watcher_operator.go
  internal/watcher/nginx_health_watcher_operator_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcherfakes/fake_health_watcher_operator.go
  test/integration/grpc_management_plane_api_test.go
  test/mock/grpc/mock_management_server.go
  test/types/config.go
Labels: chore

#685 Parse NGINX config and update NGINX instances with config context
  Makefile
  files/file_helpers.go
  files/file_helpers_test.go
  go.mod
  internal/bus/topics.go
  internal/config/types.go
  internal/model/config.go
  internal/watcher/instance_watcher_service.go
  internal/watcher/instance_watcher_service_test.go
  internal/watcher/nginx_config_parser.go
  internal/watcher/nginx_config_parser_benchmark_test.go
  internal/watcher/nginx_config_parser_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
  internal/watcher/watcherfakes/fake_nginx_config_parser.go
Labels: dependencies, chore

#686 Add Instance Children & Worker Processes
  .github/workflows/ci.yml
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  go.mod
  internal/service/instance/nginx_instance_service_test.go
  internal/watcher/instance_watcher_service.go
  internal/watcher/instance_watcher_service_test.go
  internal/watcher/nginx_process_parser.go
  internal/watcher/nginx_process_parser_test.go
  internal/watcher/watcherfakes/fake_process_parser.go
  test/protos/instances.go
  test/protos/process.go
Labels: documentation, dependencies, chore

#689 Change environment variable list to table with CLI references
  site/content/configuration/configuration-overview.md
  site/content/installation-upgrade/container-environments/docker-images.md
Labels: documentation

#673 Add health checks documentation
  site/content/configuration/configuration-overview.md
  site/content/configuration/health-checks.md
Labels: documentation, dependencies, chore

#691 Report instance updates
  internal/watcher/instance_watcher_service.go
  internal/watcher/instance_watcher_service_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
Labels: chore

#693 Update changelog for release 2.34
  site/content/changelog.md
Labels: documentation

#687 Switch over to new instance watcher service
  Makefile
  internal/bus/topics.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/datasource/host/process.go
  internal/datasource/host/process_benchmark_test.go
  internal/datasource/host/process_test.go
  internal/metrics/export/otel.go
  internal/metrics/export/otel_test.go
  internal/metrics/source/prometheus/convert.go
  internal/metrics/source/prometheus/convert_test.go
  internal/metrics/source/prometheus/prometheus.go
  internal/metrics/source/prometheus/prometheus_test.go
  internal/metrics/source/prometheus/prometheus_test_data.txt
  internal/model/metrics.go
  internal/model/metrics_test.go
  internal/model/modelfakes/fake_exporter.go
  internal/model/modelfakes/fake_metrics_producer.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/metrics_plugin.go
  internal/plugin/metrics_plugin_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/plugin/process_monitor_plugin.go
  internal/plugin/process_monitor_plugin_test.go
  internal/plugin/resource_plugin.go
  internal/plugin/resource_plugin_test.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/resource/resourcefakes/fake_resource_service_interface.go
  internal/service/instance/agent_instance_service.go
  internal/service/instance/agent_instance_service_test.go
  internal/service/instance/data_plane_instance_service.go
  internal/service/instance/instancefakes/fake_data_plane_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service_test.go
  internal/service/instance/nginx_instance_service.go
  internal/service/instance/nginx_instance_service_benchmark_test.go
  internal/service/instance/nginx_instance_service_test.go
  internal/service/instance_service.go
  internal/service/instance_service_test.go
  internal/service/resource_service.go
  internal/service/resource_service_test.go
  internal/service/servicefakes/fake_instance_service_interface.go
  internal/service/servicefakes/fake_resource_service_interface.go
  internal/watcher/health_watcher_service.go
  internal/watcher/nginx_config_parser.go
  nginx-agent.conf
  test/protos/resource.go
  test/types/config.go
Labels: chore

#694 Add file plugin
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/common.proto
  docs/proto/protos.md
  internal/bus/topics.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/types.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/grpc/grpcfakes/fake_grpc_connection_interface.go
  internal/plugin/grpc_client_plugin.go
  internal/plugin/grpc_client_plugin_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
  test/types/config.go
Labels: documentation, chore

#651 Add agent v3 packaging & release workflows
  .github/workflows/build-package.yml
  .github/workflows/release.yml
  .nfpm.yaml
  Makefile
  Makefile.packaging
  scripts/nginx-agent.logrotate
  scripts/packages/packager/local-entrypoint.sh
  scripts/packages/packager/signed-entrypoint.sh
Labels: chore
