Repository nginx/agent, pull requests merged in 2024-02, with the labels that each got.

#553 feat: move NMS agent docs
  site/content/configuration/configuration-overview.md
  site/content/configuration/configure-nginx-agent-group.md
  site/content/configuration/encrypt-communication.md
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/installation-upgrade/container-environments/docker-support.md
  site/content/technical-specifications.md
  site/go.mod
  site/go.sum
Labels: documentation, enhancement, dependencies

#556 Draft: Add Unit-Test and Unsigned Snapshots to pipeline
  .github/workflows/ci.yml
  Makefile
  go.mod
  go.sum
  scripts/packages/.local-nfpm.yaml
Labels: dependencies

#560 Reduce code complexity
  .golangci.yml
  internal/bus/fake_message_pipe.go
  internal/bus/message_pipe.go
  internal/datasource/config/config_writer.go
  internal/service/config/nginx.go
  internal/service/instance.go
  internal/service/instance/instance.go
  internal/service/instance/instancefakes/fake_dataplane_instance_service.go
  internal/service/instance/nginx.go
  internal/service/instance/nginx_gateway_fabric.go
  internal/service/instance/nginx_test.go
  internal/service/instance_test.go
Labels: chore

#558 Fix artifact name
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
Labels: bug

#563 Add allowed dir list
  internal/client/clientfakes/fake_config_client_interface.go
  internal/client/http_config_client.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  nginx-agent.conf
Labels: chore

#564 bump vulnerable version of buildkit
  go.work.sum
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/github.com/moby/buildkit/client/client.go
  test/integration/vendor/github.com/moby/buildkit/client/llb/sourcemap.go
  test/integration/vendor/github.com/moby/buildkit/exporter/containerimage/exptypes/parse.go
  test/integration/vendor/github.com/moby/buildkit/frontend/gateway/client/attestation.go
  test/integration/vendor/github.com/moby/buildkit/util/entitlements/entitlements.go
  test/integration/vendor/github.com/moby/buildkit/util/tracing/detect/detect.go
  test/integration/vendor/modules.txt
Labels: dependencies, chore

#552 Add configuration status endpoint
  .github/workflows/ci.yml
  Makefile
  Makefile.tools
  api/grpc/instances/configurations.pb.go
  api/grpc/instances/configurations.proto
  api/grpc/instances/file.pb.go
  api/grpc/instances/file.proto
  api/grpc/instances/instances.pb.go
  api/grpc/instances/instances.proto
  api/http/common/common.gen.go
  api/http/common/common.yaml
  api/http/dataplane/client.gen.go
  api/http/dataplane/dataplane-api.yaml
  api/http/dataplane/dataplane.gen.go
  api/http/dataplane/error.go
  api/http/dataplane/error_test.go
  go.mod
  go.sum
  internal/bus/topics.go
  internal/plugin/config.go
  internal/plugin/config_test.go
  internal/plugin/dataplane_server.go
  internal/plugin/dataplane_server_test.go
  internal/service/config.go
  internal/service/config/nginx_gateway_fabric_test.go
  internal/service/instance.go
  internal/service/instance/nginx_gateway_fabric_test.go
  internal/service/instance_test.go
  internal/service/servicefakes/fake_config_service_interface.go
  internal/service/servicefakes/fake_instance_service_interface.go
Labels: dependencies, chore

#566 Refactor plugins to remove unnecessary paramaters
  internal/plugin/dataplane_server.go
  internal/plugin/dataplane_server_test.go
  internal/plugin/instance.go
  internal/plugin/instance_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/process_monitor.go
  internal/plugin/process_monitor_test.go
Labels: chore

#570 feat: import changelog from github
  site/content/changelog.md
Labels: documentation, enhancement

#569 Add integration tests for get instances endpoint
  .github/workflows/ci.yml
  Makefile
  Makefile.containers
  api/http/dataplane/client.gen.go
  api/http/dataplane/dataplane-api.yaml
  go.mod
  go.sum
  internal/plugin/dataplane_server_plugin.go
  scripts/docker/entrypoint.sh
  scripts/docker/nginx-oss/apk/Dockerfile
  scripts/docker/nginx-oss/deb/Dockerfile
  scripts/docker/nginx-oss/rpm/Dockerfile
  scripts/packages/.local-nfpm.yaml
  test/integration/dataplane_api_test.go
  test/integration/nginx-agent.conf
  test/integration/nginx.conf
  test/integration/utils/test_containers_utils.go
Labels: dependencies, chore

#568 Add new unit test coverage
  api/http/dataplane/error_test.go
  internal/client/http_config_client_test.go
  internal/config/config_test.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/host/file_helpers_test.go
  internal/logger/logger_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/data_plane_server_test.go
  internal/plugin/instance_plugin_test.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/config/dataplane_config_service.go
  internal/service/config/dataplane_config_service_test.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  test/data.go
  test/helpers.go
Labels: chore

#572 fix: add missing catalog entry
  site/content/installation-upgrade/container-environments/docker-images.md
Labels: bug, documentation

#573 Add mock management plane API
  Makefile
  internal/service/config/nginx_config_service_test.go
  test/cmd/main.go
  test/config/nginx/nginx-with-multiple-access-logs.conf
  test/config/nginx/nginx.conf
  test/config/nginx_config.go
  test/integration/dataplane_api_test.go
  test/mock/mock-management-plane-api.yaml
  test/mock/mock_management_plane.gen.go
  test/mock/mock_management_plane_server.go
  test/utils/test_containers_utils.go
Labels: chore

#571 Update Config Writer & Add UpdateInstanceConfiguration
  .golangci.yml
  Makefile.tools
  internal/client/clientfakes/fake_config_client_interface.go
  internal/client/http_config_client.go
  internal/client/http_config_client_test.go
  internal/config/config.go
  internal/datasource/config/cache.go
  internal/datasource/config/cache_test.go
  internal/datasource/config/config_writer.go
  internal/datasource/config/config_writer_test.go
  internal/datasource/config/configfakes/fake_config_writer_interface.go
  internal/datasource/config/configfakes/fake_file_cache_interface.go
  internal/plugin/config_plugin.go
  internal/plugin/config_plugin_test.go
  internal/plugin/data_plane_server.go
  internal/plugin/plugin_manager.go
  internal/plugin/process_monitor_plugin.go
  internal/service/config/configfakes/fake_data_plane_config.go
  internal/service/config/dataplane_config_service.go
  internal/service/config/nginx_config_service.go
  internal/service/config/nginx_config_service_test.go
  internal/service/config/nginx_gateway_fabric.go
  internal/service/config/nginx_gateway_fabric_test.go
  internal/service/config_service.go
  internal/service/config_service_test.go
  internal/service/servicefakes/fake_config_service_interface.go
  test/helpers.go
  test/mock/mock_management_plane_server.go
Labels: chore

#583 change log updated for last release
  site/content/changelog.md
Labels: documentation

#579 Rename Dataplane to DataPlane
  Makefile
  api/http/dataplane/data-plane-api.yaml
  api/http/dataplane/data_plane.gen.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/plugin/data_plane_server.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/service/config/data_plane_config_service.go
  internal/service/config/data_plane_config_service_test.go
  internal/service/config/nginx_gateway_fabric_config_service.go
  internal/service/config/nginx_gateway_fabric_config_service_test.go
  internal/service/config_service_test.go
  internal/service/instance/data_plane_instance_service.go
  internal/service/instance/instancefakes/fake_dataplane_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service.go
  internal/service/instance/nginx_gateway_fabric_instance_service_test.go
  internal/service/instance_service.go
  internal/service/instance_service_test.go
  nginx-agent.conf
  test/integration/data_plane_api_test.go
  test/integration/nginx-agent.conf
Labels: chore

#577 test: add go-test-coverage
  .github/workflows/ci.yml
  .testcoverage.yaml
  Makefile
  Makefile.tools
  README.md
  internal/client/http_config_client_test.go
  internal/datasource/host/exec/exec_test.go
  internal/datasource/host/process_test.go
Labels: documentation, github_actions
