Repository nginx/agent, pull requests merged in 2025-04, with the labels that each got.

#1028 Update golang.org/x/net version
  go.mod
  go.sum
  go.work.sum
  sdk/go.mod
  sdk/go.sum
  sdk/vendor/modules.txt
  test/integration/go.mod
  test/integration/go.sum
  test/integration/vendor/modules.txt
  test/performance/go.mod
  test/performance/go.sum
  test/performance/vendor/modules.txt
  vendor/modules.txt
Labels: dependencies, v2.x

#1020 Adds memory limit metrics
  internal/collector/otelcol.tmpl
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/grafana/provisioning/dashboards/host-metrics.json
Labels: v3.x

#1034 Update golang toolchain version to 1.23.8
  go.mod
Labels: dependencies, v3.x

#1035 Update golang toolchain to 1.23.8
  go.mod
Labels: v2.x

#1033 Added manifest file
  .nfpm.yaml
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/model/config.go
  scripts/packages/.local-nfpm.yaml
  test/protos/files.go
Labels: chore, v3.x

#1018 Shutdown gracefully
  cmd/agent/main.go
  internal/config/config.go
  test/docker/entrypoint.sh
  test/docker/nginxless-entrypoint.sh
Labels: chore, v3.x

#1037 Review file permission for otel collector config
  internal/collector/settings.go
  internal/collector/settings_test.go
Labels: chore, v3.x

#1049 Merge v2.40.1 back to main
  src/core/metrics/metrics_util.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/metrics_util.go
Labels: dependencies, chore, v2.x

#1041 Fix naming of HTTP Metrics and add request & response count metrics
  internal/collector/nginxossreceiver/documentation.md
  internal/collector/nginxossreceiver/internal/metadata/generated_config.go
  internal/collector/nginxossreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxossreceiver/internal/metadata/testdata/config.yaml
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/testdata/expected.yaml
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper_test.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/testdata/expected.yaml
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/testdata/expected_with_connections_as_gauge.yaml
  internal/collector/nginxossreceiver/metadata.yaml
  internal/collector/nginxplusreceiver/documentation.md
  internal/collector/nginxplusreceiver/internal/metadata/generated_config.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/internal/metadata/testdata/config.yaml
  internal/collector/nginxplusreceiver/metadata.yaml
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/nginxplusreceiver/scraper_test.go
  internal/collector/nginxplusreceiver/testdata/expected.yaml
  test/mock/collector/grafana/provisioning/dashboards/nginx-dashboard.json
  test/mock/collector/grafana/provisioning/dashboards/nginx-plus-dashboard.json
Labels: bug, documentation, chore, v3.x

#1044 enable default collector
  internal/config/config.go
  internal/config/types.go
  internal/datasource/file/file.go
  internal/datasource/file/file_test.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/plugin/plugin_manager.go
  scripts/packages/preinstall.sh
  scripts/packages/upgrade-agent-config.sh
Labels: chore, v3.x

#1054 Add unit test for stderr/stdout error log
  internal/watcher/instance/nginx_config_parser_test.go
  test/model/config.go
Labels: chore, v3.x

#1039 Add NGINX Agent config validation
  go.mod
  go.sum
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/mapper.go
  internal/config/mapper_test.go
  internal/config/testdata/invalid-format-nginx-agent.conf
  internal/config/testdata/nginx-agent.conf
  internal/config/testdata/unknown-field-nginx-agent.conf
  internal/config/types.go
  nginx-agent.conf
  test/config/agent/nginx-agent-otel-load.conf
  test/config/agent/nginx-config-with-grpc-client.conf
  test/types/config.go
Labels: dependencies, chore, v3.x

#1050 Add config parser tests for SSLCerts
  internal/watcher/instance/nginx_config_parser_test.go
  test/config/nginx/nginx-with-multiple-ssl-certs.conf
  test/config/nginx/nginx-with-ssl-certs.conf
  test/config/nginx_config.go
  test/model/config.go
Labels: chore, v3.x

#1051 Enable/Disable Features
  internal/collector/otel_collector_plugin.go
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/config/config.go
  internal/config/defaults.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/watcher_plugin.go
  pkg/config/features.go
Labels: enhancement, chore, v3.x

#1058 Ignore NGINX cache manager process when looking for NGINX master process
  internal/watcher/file/file_watcher_service.go
  internal/watcher/instance/nginx_process_parser.go
  internal/watcher/instance/nginx_process_parser_test.go
Labels: bug, chore

#1063 Clean up log level documentation
  internal/config/config.go
  test/config/agent/nginx-agent-otel-load.conf
  test/mock/collector/nginx-agent.conf
Labels: chore, v3.x

#1061 Update OTel dependencies
  go.mod
  go.sum
  internal/collector/factories.go
  internal/collector/nginxossreceiver/factory.go
  internal/collector/nginxossreceiver/factory_test.go
  internal/collector/nginxossreceiver/generated_component_test.go
  internal/collector/nginxossreceiver/internal/config/config.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_resource_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/config.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/input.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/input_test.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper_test.go
  internal/collector/nginxplusreceiver/config.go
  internal/collector/nginxplusreceiver/factory.go
  internal/collector/nginxplusreceiver/generated_component_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_resource_test.go
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/nginxplusreceiver/scraper_test.go
  internal/grpc/grpc.go
  test/helpers/network_utils.go
  test/load/nginx_agent_process_collector.go
  test/mock/collector/mock-collector/auth/auth.go
  test/mock/collector/mock-collector/main.go
Labels: dependencies, chore, v3.x

#1056 Fix upgrade v2 to v3
  scripts/packages/preinstall.sh
Labels: bug, v3.x
