Repository nginx/agent, pull requests merged in 2025-01, with the labels that each got.

#961 Fix apk test package naming
  Makefile.packaging
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
Labels: bug, chore, v3.x

#959 Update agent config defaults and format
  internal/backoff/backoff.go
  internal/backoff/backoff_test.go
  internal/collector/otel_collector_plugin.go
  internal/command/command_service.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/file/file_manager_service.go
  internal/grpc/grpc.go
  internal/resource/resource_plugin_test.go
  internal/watcher/instance/nginx_config_parser.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_server.go
  test/types/config.go
Labels: chore

#949 Add config apply request queue
  internal/command/command_service.go
  internal/command/command_service_test.go
Labels: chore, v3.x

#964 Add unmanaged option to file proto
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
Labels: documentation, chore

#945 Add labels to Agent Configuration
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/helpers.go
  api/grpc/mpi/v1/helpers_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/watcher/instance/instance_watcher_service.go
Labels: chore, v3.x

#955 Add nginx plus api actions
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/datasource/proto/message.go
  internal/resource/nginx_plus_actions.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/resource/resourcefakes/fake_resource_service_interface.go
  test/helpers/nginx_plus.go
  test/mock/grpc/README.md
  test/protos/management_plane_request.go
Labels: documentation, chore

#967 Send create connection after disconnect from management plane
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/resource/resource_service.go
  test/integration/grpc_management_plane_api_test.go
Labels: chore

#968 fix: flaky test
  api/grpc/mpi/v1/helpers_test.go
Labels: bug, chore

#958 Add token path to Agent config Command block
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/common.pb.validate.go
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  internal/config/config.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/grpc/grpcfakes/fake_grpc_connection_interface.go
  test/types/config.go
Labels: chore, v3.x
