Repository nginx/agent, pull requests merged in 2025-03, with the labels that each got.

#1001 Fix failing integration tests
  test/integration/grpc_management_plane_api_test.go
Labels: bug, chore

#993 Use timeout value from config for http client
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxplusreceiver/scraper.go
  internal/watcher/instance/nginx_config_parser.go
Labels: chore

#987 Remove unsupported from agent v3 install
  scripts/packages/postinstall.sh
  scripts/packages/postremove.sh
  scripts/packages/preinstall.sh
Labels: v3.x

#942 Report NGINX App Protect instances
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/watcher/health/health_watcher_service.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/instance_watcher_service_test.go
  internal/watcher/instance/nginx_app_protect_process_parser.go
  internal/watcher/instance/nginx_app_protect_process_parser_test.go
  internal/watcher/process/process_operator.go
  internal/watcher/process/processfakes/fake_process_operator_interface.go
  pkg/nginxprocess/process.go
  test/integration/grpc_management_plane_api_test.go
Labels: documentation, chore, v3.x

#996 Update metric names for Otel conventions
  internal/collector/nginxossreceiver/documentation.md
  internal/collector/nginxossreceiver/internal/metadata/generated_config.go
  internal/collector/nginxossreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxossreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxossreceiver/internal/metadata/testdata/config.yaml
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/testdata/expected.yaml
  internal/collector/nginxossreceiver/metadata.yaml
  internal/collector/nginxplusreceiver/documentation.md
  internal/collector/nginxplusreceiver/internal/metadata/generated_config.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_config_test.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics.go
  internal/collector/nginxplusreceiver/internal/metadata/generated_metrics_test.go
  internal/collector/nginxplusreceiver/internal/metadata/testdata/config.yaml
  internal/collector/nginxplusreceiver/metadata.yaml
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/nginxplusreceiver/testdata/expected.yaml
  test/mock/collector/grafana/provisioning/dashboards/nginx-plus-dashboard.json
Labels: documentation, chore

#982 Fix Lua Parsing
  internal/watcher/instance/nginx_config_parser.go
  test/config/nginx/nginx-with-multiple-access-logs.conf
Labels: bug, chore, v3.x

#1004 Support connection reset when changes detected in TLS cert files
  internal/watcher/credentials/credential_watcher_service.go
  internal/watcher/credentials/credential_watcher_service_test.go
Labels: chore, v3.x

#1006 Add error & label to log
  internal/config/config.go
Labels: chore, v3.x

#1011 Send create connection after updating credentials
  internal/command/command_plugin.go
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/command/commandfakes/fake_command_service.go
  internal/file/file_plugin.go
  internal/grpc/grpc.go
  internal/resource/resource_plugin.go
  internal/watcher/watcher_plugin.go
Labels: chore

#1010 Enabled the cpu utilization and logical count metrics
  internal/collector/otelcol.tmpl
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/grafana/provisioning/dashboards/host-metrics.json
Labels: chore

#999 Update preinstall script to update agent config from V2 to V3
  internal/collector/otelcol.tmpl
  scripts/packages/preinstall.sh
  scripts/packages/upgrade-agent-config.sh
  test/docker/nginx-official-image/apk/Dockerfile
  test/docker/nginx-official-image/deb/Dockerfile
Labels: v3.x

#1007 Check allowed dir
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types_test.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  test/config/nginx/nginx-not-allowed-dir.conf
  test/config/nginx_config.go
  test/model/config.go
Labels: chore, v3.x

#1002 Add stream file transfer
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files.proto
  api/grpc/mpi/v1/files_grpc.pb.go
  api/grpc/mpi/v1/mocks.go
  api/grpc/mpi/v1/v1fakes/fake_file_service_client.go
  api/grpc/mpi/v1/v1fakes/fake_file_service_get_file_stream_client.go
  api/grpc/mpi/v1/v1fakes/fake_file_service_get_file_stream_server.go
  docs/proto/protos.md
  pkg/files/file_helpers_test.go
  pkg/files/file_stream.go
  pkg/files/file_stream_test.go
Labels: documentation, chore, v3.x

#1017 Update agent landing page and readme
  README.md
Labels: documentation

#1016 Migrate instance group to config sync group during V2 to V3 upgrade
  scripts/packages/preinstall.sh
Labels: v3.x

#1021 Add alpine 3.21 support
  Makefile
  Makefile.packaging
Labels: v3.x

#1024 Remove GOPROXY from release branch workflow
  .github/workflows/release-branch.yml
Labels: v3.x

#1025 Log number of potential urls found
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  internal/watcher/instance/nginx_config_parser.go
Labels: chore
