Repository nginx/agent, pull requests merged in 2025-08, with the labels that each got.

#1200 [CI/CD] Various fixes
  .github/workflows/ci.yml
  Makefile
Labels: bug, v3.x

#1208 Fix threshold values and typo in ci.yml
  .github/workflows/ci.yml
Labels: bug

#1214 Update toolchain version to 1.23.12
  go.mod
Labels: dependencies, v2.x

#1182 Move `datasource/host` to `pkg`
  go.mod
  internal/config/config.go
  internal/datasource/nginx/process.go
  internal/datasource/nginx/process_test.go
  internal/grpc/grpc.go
  internal/resource/nginx_instance_operator.go
  internal/resource/nginx_instance_operator_test.go
  internal/resource/nginx_instance_process_operator.go
  internal/resource/nginx_instance_process_operator_test.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/resource/resourcefakes/fake_process_operator.go
  internal/watcher/health/nginx_health_watcher_operator.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/instance_watcher_service_test.go
  internal/watcher/instance/nginx_process_parser.go
  internal/watcher/instance/nginx_process_parser_test.go
  pkg/host/exec/exec.go
  pkg/host/exec/exec_test.go
  pkg/host/exec/execfakes/fake_exec_interface.go
  pkg/host/hostfakes/fake_info_interface.go
  pkg/host/info.go
  pkg/host/info_test.go
Labels: dependencies, chore, v3.x

#1221 Fix performance test output
  Makefile
Labels: v3.x

#1220 Add config path to FileOverview
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.pb.validate.go
  api/grpc/mpi/v1/files.proto
  docs/proto/protos.md
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/nginx/process.go
  internal/file/file_manager_service.go
  internal/file/file_service_operator.go
  internal/file/file_service_operator_test.go
  internal/model/config.go
  internal/resource/nginx_instance_operator_test.go
Labels: documentation, chore

#1223 Find NGINX worker processes in Debug mode
  pkg/nginxprocess/process.go
  pkg/nginxprocess/process_test.go
Labels: chore

#1218 Update systemd unit file
  scripts/packages/nginx-agent.service
  scripts/packages/postinstall.sh
Labels: v3.x

#1222 Add v2 to v3 upgrade tests
  Makefile
  scripts/workflow/generate_results.sh
  test/docker/nginx-official-image/deb/Dockerfile
  test/docker/nginx-oss/deb/Dockerfile
  test/docker/nginx-oss/rpm/Dockerfile
  test/integration/upgrade/nginx-oss.conf
  test/integration/upgrade/nginx-plus.conf
  test/integration/upgrade/test_configs/nginx-agent.conf
  test/integration/upgrade/test_configs/valid-v3-nginx-agent.conf
  test/integration/upgrade/upgrade_test.go
  test/integration/utils/test_container_utils.go
Labels: chore, v2.x
