Repository nginx/agent, pull requests merged in 2025-02, with the labels that each got.

#957 Updates the timezone to utc for tcplog receiver
  internal/collector/otel_collector_plugin.go
Labels: chore

#972 docs: theme bump
  site/go.mod
  site/go.sum
Labels: dependencies

#969 Start subscribe after successful create connection request
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/command/commandfakes/fake_command_service.go
Labels: chore

#966 Add agent config test & fix watcher settings
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  test/types/config.go
Labels: bug, chore

#973 Ignore stdout & stderr logs and log warning
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/common.pb.go
  api/grpc/mpi/v1/files.pb.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
Labels: chore

#976 docs: remove docs
  .github/workflows/docs-build-push.yml
  site/.gitignore
  site/Makefile
  site/README.md
  site/config/_default/config.toml
  site/config/development/config.toml
  site/config/docker/config.toml
  site/config/production/config.toml
  site/config/staging/config.toml
  site/content/_index.md
  site/content/changelog.md
  site/content/configuration/_index.md
  site/content/configuration/configuration-overview.md
  site/content/configuration/configure-nginx-agent-features.md
  site/content/configuration/configure-nginx-agent-group.md
  site/content/configuration/encrypt-communication.md
  site/content/configuration/health-checks.md
  site/content/contribute/_index.md
  site/content/contribute/community.md
  site/content/contribute/dev-environment-setup.md
  site/content/installation-upgrade/_index.md
  site/content/installation-upgrade/container-environments/_index.md
  site/content/installation-upgrade/container-environments/docker-images.md
  site/content/installation-upgrade/container-environments/docker-support.md
  site/content/installation-upgrade/getting-started.md
  site/content/installation-upgrade/installation-github.md
  site/content/installation-upgrade/installation-oss.md
  site/content/installation-upgrade/installation-plus.md
  site/content/installation-upgrade/uninstall.md
  site/content/installation-upgrade/upgrade.md
  site/content/overview.md
  site/content/technical-specifications.md
  site/data/.gitkeep
  site/data/layouts/.gitkeep
  site/go.mod
  site/go.sum
  site/go.work
  site/go.work.sum
  site/hugo-entrypoint.sh
  site/md-linkcheck-config.json
  site/mdlint.json
  site/static/.gitkeep
  site/static/agent-flow.png
  site/static/grafana-dashboard-example.png
Labels: documentation, dependencies

#963 Lua config apply
  sdk/config_helpers.go
  sdk/config_helpers_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
Labels: documentation, dependencies, chore

#983 Update agent sdk dependency
  test/integration/go.mod
  test/integration/vendor/modules.txt
  test/performance/go.mod
  test/performance/vendor/modules.txt
Labels: dependencies

#984 Update performance test dependencies
  test/performance/go.mod
  test/performance/vendor/modules.txt
Labels: dependencies, chore

#981 Fix watcher & resource race conditions
  internal/resource/resource_plugin.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  internal/resource/resourcefakes/fake_resource_service_interface.go
  internal/watcher/health/health_watcher_service.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/watcher_plugin.go
  test/config/nginx/nginx-plus.conf
  test/helpers/test_containers_utils.go
  test/integration/grpc_management_plane_api_test.go
Labels: bug, chore

#990 Remove Changelog Generation
  .github/workflows/release-branch.yml
  go.sum
  go.work.sum
  sdk/go.mod
  sdk/go.sum
  sdk/vendor/modules.txt
  test/integration/go.sum
  test/performance/go.sum
  vendor/modules.txt
Labels: dependencies

#991 Fix release workflow
  .github/workflows/release-branch.yml
Labels: bug

#988 Remove duplicate entires of certs in files
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
Labels: chore

#975 Add Exclude Files to File Watcher & Switch to Regex for Exclude Logs
  internal/config/config.go
  internal/config/config_test.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  internal/watcher/file/file_watcher_service.go
  internal/watcher/file/file_watcher_service_test.go
  internal/watcher/instance/nginx_config_parser.go
  internal/watcher/instance/nginx_config_parser_test.go
  test/types/config.go
Labels: chore

#992 Cert common name validation
  api/grpc/mpi/v1/files.pb.go
  api/grpc/mpi/v1/files.proto
Labels: chore
