Repository nginx/agent, pull requests merged in 2025-05, with the labels that each got.

#1072 Fix to start the NGINX plus scraper
  internal/collector/nginxplusreceiver/factory.go
  internal/config/types.go
  test/mock/collector/nginx-agent.conf
Labels: bug, chore, v3.x

#1045 Change hash generation
  pkg/files/file_helpers.go
  pkg/files/file_helpers_test.go
Labels: chore, v3.x

#1073 Add setting config path from NGINX process
  internal/collector/nginxplusreceiver/factory.go
  internal/watcher/instance/nginx_process_parser.go
  internal/watcher/instance/nginx_process_parser_test.go
Labels: chore, v3.x

#1071 CI: remove release workflow call on all v3 pipelines
  .github/workflows/ci.yml
  .github/workflows/release-branch.yml
Labels: chore, v3.x

#1075 Update Manifest file during a ConfigContextUpdate
  internal/config/config.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
  internal/model/config.go
  internal/watcher/watcher_plugin.go
  test/helpers/os_utils.go
Labels: chore, v3.x

#1080 Update Default Backoff Settings
  internal/config/defaults.go
  test/docker/load/Dockerfile
Labels: chore

#1065 Fix names and default values of Agent Config settings.
  README.md
  internal/collector/nginxossreceiver/metadata.yaml
  internal/collector/nginxplusreceiver/metadata.yaml
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/collector/settings_test.go
  internal/config/config_test.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
  test/config/agent/nginx-agent-otel-load.conf
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/mock/collector/nginx-agent.conf
Labels: bug, documentation, chore, v3.x

#1086 Allow underscores in hostname
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.proto
Labels: chore, v3.x

#1085 OTel Logs to Stdout in Containers
  internal/collector/otel_collector_plugin.go
  internal/collector/otelcol.tmpl
  internal/config/config.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
Labels: chore, v3.x

#1090 Remove symbol table from build
  Makefile
Labels: chore, v3.x

#1088 Fix remotely enabling/disabling features
  Makefile
  src/core/environment.go
  src/core/metrics/collectors/nginx.go
  src/core/metrics/sources/nginx_plus.go
  src/core/pipe.go
  src/plugins/agent_api.go
  src/plugins/commander.go
  src/plugins/common.go
  src/plugins/config_reader.go
  src/plugins/dataplane_status.go
  src/plugins/events.go
  src/plugins/extensions.go
  src/plugins/features.go
  src/plugins/features_test.go
  src/plugins/file_watcher.go
  src/plugins/file_watcher_throttling.go
  src/plugins/metrics.go
  src/plugins/metrics_sender.go
  src/plugins/metrics_sender_test.go
  src/plugins/metrics_throlling.go
  src/plugins/nginx.go
  src/plugins/nginx_counter.go
  src/plugins/process_watcher.go
  src/plugins/registration.go
  test/component/nginx-app-protect/monitoring/monitoring_test.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/metrics_test.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/environment.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/pipe.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/agent_api.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/commander.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/common.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/config_reader.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/dataplane_status.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/events.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/extensions.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/features.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/file_watcher.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/file_watcher_throttling.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_sender.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/metrics_throlling.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/nginx_counter.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/process_watcher.go
  test/performance/vendor/github.com/nginx/agent/v2/src/plugins/registration.go
Labels: bug, enhancement, dependencies, chore, v2.x

#1098 Remove Ubuntu 22.04 integration test
  .github/workflows/ci.yml
Labels: v3.x

#1096 Fix request count metric for NGINX Plus receiver
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/nginxplusreceiver/scraper_test.go
  internal/collector/nginxplusreceiver/testdata/expected.yaml
Labels: bug, chore, v3.x

#1095 Fix purging of dirs and files
  scripts/packages/postremove.sh
Labels: bug, v3.x

#1097 Ignore Access Log in metrics collection if Formats differ
  internal/collector/otel_collector_plugin.go
  internal/command/command_plugin_test.go
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/config/nginx_config_parser_test.go
  internal/watcher/process/process_operator.go
Labels: chore

#1100 Fix to allow multiple access logs to collect metrics
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper_test.go
Labels: bug, chore
