Repository nginx/agent, pull requests merged in 2025-06, with the labels that each got.

#1112 Update branch name references from main to dev-v2
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/scorecards.yml
  CONTRIBUTING.md
  test/docker/nginx-official-image/deb/Dockerfile
Labels: documentation, v2.x

#1111 Changed README to reflect new community forum
  README.md
Labels: documentation, chore, v3.x

#1081 Update linter version and install instructions in README.md
  .golangci.yml
  Makefile.tools
  README.md
  internal/datasource/host/info_test.go
Labels: bug, documentation, chore, v3.x

#1114 Remove scorecard workflow
  .github/workflows/scorecards.yml
Labels: v2.x

#1093 Update codeql workflow to use common codeql rules
  .github/workflows/codeql.yml
Labels: chore, v2.x

#1115 Update github workflows
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/label-pr.yml
  .github/workflows/release-branch.yml
Labels: v3.x

#1116 Allow only CA cert to be set in command server TLS settings
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  test/helpers/cert_utils.go
Labels: chore, v3.x

#1110 Update mock collector grafana dashboards
  internal/collector/containermetricsreceiver/internal/scraper/cpuscraper/scraper.go
  test/mock/collector/grafana/provisioning/dashboards/host-metrics.json
  test/mock/collector/grafana/provisioning/dashboards/nginx-dashboard.json
  test/mock/collector/grafana/provisioning/dashboards/nginx-plus-dashboard.json
Labels: chore, v3.x

#1104 Add source to logs in Debug Mode & Clean up function names
  internal/bus/busfakes/fake_message_pipe.go
  internal/bus/message_pipe.go
  internal/bus/message_pipe_test.go
  internal/collector/containermetricsreceiver/internal/scraper/cpuscraper/internal/cgroup/cpu.go
  internal/collector/containermetricsreceiver/internal/scraper/memoryscraper/internal/cgroup/memory.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/command/command_plugin.go
  internal/command/command_plugin_test.go
  internal/command/command_service.go
  internal/command/command_service_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/config/mapper_test.go
  internal/config/types_test.go
  internal/datasource/config/nginx_config_parser_test.go
  internal/datasource/host/info.go
  internal/datasource/proto/instance_test.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/grpc/grpc.go
  internal/grpc/grpc_test.go
  internal/logger/logger.go
  internal/logger/logger_test.go
  internal/resource/nginx_instance_operator_test.go
  internal/resource/nginx_plus_actions.go
  internal/resource/resource_plugin.go
  internal/resource/resource_plugin_test.go
  internal/resource/resource_service_test.go
  internal/watcher/credentials/credential_watcher_service.go
  internal/watcher/file/file_watcher_service.go
  internal/watcher/health/health_watcher_service.go
  internal/watcher/health/health_watcher_service_test.go
  internal/watcher/health/nginx_health_watcher_operator_test.go
  internal/watcher/instance/instance_watcher_service.go
  internal/watcher/instance/instance_watcher_service_test.go
  internal/watcher/instance/nginx_process_parser.go
  internal/watcher/instance/nginx_process_parser_test.go
  internal/watcher/watcher_plugin.go
  internal/watcher/watcher_plugin_test.go
  test/config/nginx_config.go
  test/helpers/go_utils.go
  test/helpers/network_utils.go
  test/integration/installuninstall/install_uninstall_test.go
  test/integration/managementplane/grpc_management_plane_api_test.go
  test/mock/grpc/cmd/main.go
  test/mock/grpc/mock_management_file_service.go
  test/mock/grpc/mock_management_server.go
  test/model/config.go
  test/protos/config.go
  test/protos/instances.go
  test/protos/resource.go
  test/types/config.go
Labels: chore, v3.x

#1118 Release 3.0.1
  internal/file/file_manager_service.go
Labels: chore

#1069 Add env variables for make dev target
  Makefile
  internal/config/config.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
Labels: chore, v3.x

#1123 Handle scenario where agent tries to delete a file that does not exist during a config apply
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
Labels: bug, v3.x

#1126 Fix debug log format
  internal/logger/logger.go
Labels: chore, v3.x

#1135 Revert "[Release 3.0.2] Merge back into main"
  go.mod
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
Labels: dependencies, chore

#1136 [Release 3.0.2] Merge back into main
  go.mod
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
Labels: dependencies, chore

#1137 [Secure Build] New workflow to pull packages
  .github/workflows/release-branch.yml
  .github/workflows/upload-release-assets.yml
Labels: v3.x

#1131 Bump golang version from 1.23.8 to 1.23.10
  go.mod
  sdk/go.mod
  test/integration/go.mod
  test/performance/go.mod
Labels: dependencies, v2.x

#1138 Add mend workflow
  .github/workflows/mend.yml
Labels: chore, v3.x

#1139 Add check to see if SSL is enabled for Plus API
  sdk/config_helpers.go
  src/core/config/config.go
  src/core/config/defaults.go
  src/core/config/types.go
  src/core/metrics/collectors/nginx.go
  src/core/metrics/sources/nginx_plus.go
  src/core/metrics/sources/nginx_plus_test.go
  test/integration/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/sdk/v2/config_helpers.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/defaults.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/types.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/collectors/nginx.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/metrics/sources/nginx_plus.go
Labels: dependencies, chore, v2.x

#1142 Update batch processor defaults
  internal/config/defaults.go
  test/config/agent/nginx-agent-otel-load.conf
  test/config/collector/test-opentelemetry-collector-agent.yaml
Labels: chore, v3.x

#1143 Update cert utils
  test/helpers/cert_utils.go
Labels: chore, v3.x

#1125 Default NAP security-violation logs to be gzipped individually via custom processor
  internal/collector/factories.go
  internal/collector/factories_test.go
  internal/collector/logsgzipprocessor/README.md
  internal/collector/logsgzipprocessor/processor.go
  internal/collector/logsgzipprocessor/processor_benchmark_test.go
  internal/collector/logsgzipprocessor/processor_test.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
  internal/config/config.go
  internal/config/config_test.go
  internal/config/flags.go
  internal/config/testdata/nginx-agent.conf
  internal/config/types.go
Labels: chore, v3.x
