Repository nginx/agent, pull requests merged in 2025-07, with the labels that each got.

#1152 Add Alpine 3.22 Support
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
Labels: chore, v2.x

#1149 Fix config format outputted by preinstall script
  go.mod
  scripts/packages/preinstall.sh
Labels: bug, dependencies, v3.x

#1153 [CI/CD] Fix debian package naming
  .github/workflows/upload-release-assets.yml
Labels: v3.x

#1154 Remove scorecard token, default to GITHUB_TOKEN
  .github/workflows/scorecards.yml
Labels: v3.x

#1128 Add read only file plugin
  internal/command/command_plugin.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  internal/file/file_operator.go
  internal/file/file_plugin.go
  internal/file/file_plugin_test.go
  internal/file/file_service_operator.go
  internal/file/file_service_operator_test.go
  internal/file/filefakes/fake_file_manager_service_interface.go
  internal/file/filefakes/fake_file_operator.go
  internal/plugin/plugin_manager.go
  internal/plugin/plugin_manager_test.go
Labels: chore, v3.x

#1156 Add more unix socket unit tests
  internal/datasource/config/nginx_config_parser_test.go
Labels: v3.x

#1161 Add support for new redhat and ubuntu os
  Makefile
  scripts/packages/package-check.sh
Labels: v3.x

#1166 Add check for nginx pid file in test docker images
  test/docker/entrypoint.sh
Labels: v3.x

#1162 Fix Agent failing to find NGINX process when NGINX is in debug
  pkg/nginxprocess/process.go
  pkg/nginxprocess/process_test.go
Labels: bug, chore, v3.x

#1165 Parse NGINX Config for Valid NAP Syslog Server
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/config/nginx_config_parser_test.go
  internal/model/config.go
  internal/resource/resource_service_test.go
  test/config/nginx/nginx-with-multiple-syslog-servers.conf
  test/config/nginx_config.go
  test/model/config.go
Labels: chore, v3.x

#1163 Add NAP paths to allowed directories
  internal/config/config_test.go
  internal/config/defaults.go
  internal/watcher/instance/nginx-app-protect-instance-watcher_test.go
  nginx-agent.conf
  scripts/packages/preinstall.sh
  scripts/packages/upgrade-agent-config.sh
Labels: dependencies, chore, v3.x

#1176 Fix Failing Unit-Test
  internal/collector/otel_collector_plugin_test.go
Labels: v3.x

#1169 Filter NAP logs by Severity
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/collector/otelcol.tmpl
Labels: chore, v3.x

#1175 Add support for ssl in v3
  api/grpc/mpi/v1/command.pb.go
  api/grpc/mpi/v1/command.pb.validate.go
  api/grpc/mpi/v1/command.proto
  docs/proto/protos.md
  internal/collector/nginxossreceiver/internal/config/config.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/stubstatus/stub_status_scraper_tls_test.go
  internal/collector/nginxplusreceiver/config.go
  internal/collector/nginxplusreceiver/scraper.go
  internal/collector/otel_collector_plugin.go
  internal/collector/otelcol.tmpl
  internal/config/config.go
  internal/config/defaults.go
  internal/config/flags.go
  internal/config/types.go
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/config/nginx_config_parser_test.go
  internal/model/config.go
  internal/resource/resource_service.go
  internal/resource/resource_service_test.go
  test/config/collector/test-opentelemetry-collector-agent.yaml
  test/helpers/cert_utils.go
Labels: documentation, chore, v3.x

#1171 Reduce integration tests execution time
  test/integration/managementplane/config_apply_test.go
  test/integration/managementplane/config_upload_test.go
  test/integration/managementplane/file_watcher_test.go
  test/integration/managementplane/grpc_management_plane_api_test.go
Labels: chore, v3.x

#1144 Add validation to allowed directories on config load
  internal/config/config.go
  internal/config/config_test.go
  internal/config/types.go
  internal/config/types_test.go
  internal/watcher/file/file_watcher_service_test.go
Labels: chore, v3.x

#1184 Fix agent version reporting
  src/core/config/config.go
  test/integration/vendor/github.com/nginx/agent/v2/src/core/config/config.go
  test/performance/vendor/github.com/nginx/agent/v2/src/core/config/config.go
Labels: bug, dependencies, chore, v2.x

#1179 Add RHEL 10 and ubuntu 25.04 support
  .github/workflows/ci.yml
  Makefile
  Makefile.packaging
  docs/proto/proto.md
  go.mod
  sdk/go.mod
  test/integration/go.mod
  test/performance/go.mod
Labels: documentation, dependencies, v2.x

#1189 Fix how NAP syslog servers are discovered
  internal/collector/otel_collector_plugin.go
  internal/collector/otel_collector_plugin_test.go
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/config/nginx_config_parser_test.go
  internal/model/config.go
  internal/resource/resource_service_test.go
  test/model/config.go
Labels: bug, chore, v3.x

#1195 Version fix
  Makefile.packaging
Labels: bug

#1186 Set OTel Collector Log Level To Match Agent
  internal/config/config.go
  internal/config/config_test.go
Labels: chore, v3.x
