Repository nginx/agent, pull requests merged in 2025-09, with the labels that each got.

#1247 Fix NGINX stub_status and plus api discovery
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/config/nginx_config_parser_test.go
Labels: bug, chore, v3.x

#1245 Add upgrade tests
  .github/workflows/ci.yml
  Makefile
  test/docker/nginx-oss/apk/Dockerfile
  test/integration/upgrade/configs/nginx-agent-v3-valid-config.conf
  test/integration/upgrade/configs/nginx-agent.conf
  test/integration/upgrade/configs/nginx-oss.conf
  test/integration/upgrade/configs/nginx-plus.conf
  test/integration/upgrade/upgrade_test.go
  test/integration/utils/config_apply_utils.go
  test/integration/utils/grpc_management_plane_utils.go
Labels: chore, v3.x

#1249 Add nil pointer check to file watcher
  internal/watcher/file/file_watcher_service.go
Labels: chore, v3.x

#1248 Ensure that a file overview update is performed even if the initial create connection request takes a long time
  internal/file/file_manager_service.go
  internal/file/file_service_operator.go
  internal/file/file_service_operator_test.go
Labels: chore, v3.x

#1283 Fix how we handle log tailing when the line is nil
  internal/datasource/nginx/log_tailer.go
Labels: bug, chore, v3.x

#1282 Update OTel dependencies
  go.mod
  go.sum
  internal/collector/logsgzipprocessor/processor_benchmark_test.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/nginx_log_scraper.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/input.go
  internal/collector/nginxossreceiver/internal/scraper/accesslog/operator/input/file/input_test.go
  test/helpers/test_containers_utils.go
Labels: dependencies, chore, v3.x

#1297 Fix Performance Benchmark for release-3.3.2
  internal/collector/logsgzipprocessor/processor_benchmark_test.go
Labels: bug, chore

#1276 Fix isAllowedDir matching by prefix
  internal/config/config_test.go
  internal/config/types.go
  internal/config/types_test.go
  internal/datasource/config/nginx_config_parser.go
  internal/datasource/config/nginx_config_parser_benchmark_test.go
  internal/file/file_manager_service.go
  internal/file/file_manager_service_test.go
  test/types/config.go
Labels: bug, chore
